### ISSUE TITLE
[BUG] - Input and dropdown are not having the styles as shown in the documentation

### ISSUE THREAD

**Issue by DarkWolff71** [nextui-org/nextui#2037] opened 2023-11-25 08:32 UTC
### NextUI Version

2.2.9

### Describe the bug

The styles of dropdown and input components are broken and are not as shown in the documentation.
Also, tried with the template provided (https://github.com/nextui-org/next-app-template), but still facing the same issue.

Versions:
node - v18.17.0
tailwind CSS - 3.3.5
framer motion - 10.16.4

### Steps to Reproduce the Bug or Issue

1. npx create-next-app my-app -e https://github.com/nextui-org/next-app-template
2. cd my-app
3. yarn
4. Add the following snippet to page.tsx:
  
      <Dropdown>
        <DropdownTrigger>
          <Button variant="bordered">Open Menu</Button>
        </DropdownTrigger>
        <DropdownMenu aria-label="Static Actions">
          <DropdownItem key="new">New file</DropdownItem>
          <DropdownItem key="copy">Copy link</DropdownItem>
          <DropdownItem key="edit">Edit file</DropdownItem>
          <DropdownItem key="delete" className="text-danger" color="danger">
            Delete file
          </DropdownItem>
        </DropdownMenu>
      </Dropdown>

      <div className="flex w-full flex-wrap md:flex-nowrap gap-4">
        <Input type="email" label="Email" placeholder="Enter your email" />
      </div>
5. yarn dev

### Expected behavior

The expected behavior should be as shown in the documentation

### Screenshots or Videos

![InputBroken](https://github.com/nextui-org/nextui/assets/145280318/d23a27fe-b199-4044-99ae-c07e5c5be387)
As shown in the image, the input and the dropdown within the red box have broken styles.

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by tom-ai** [comment] 2023-12-27 22:02
Same here! Currently adding `style={{ backgroundColor: "transparent" }}` to the component to display properly

**Comment by wingkwong** [comment] 2024-07-24 06:01
Closing - no reproducible. The styles from the screenshots looks like you missed [this step](https://github.com/nextui-org/next-app-template?tab=readme-ov-file#setup-pnpm-optional).

**Closed by wingkwong** 2024-07-24 06:01 UTC
Labels: 🐛 Type: Bug
