### ISSUE TITLE
[BUG] - DatePicker on Firefox

### ISSUE THREAD

**Issue by RibeyrollesMatthieu** [nextui-org/nextui#3072] opened 2024-05-24 11:21 UTC
### NextUI Version

2.3.6

### Describe the bug

When setting up a DatePicker (the exact same way as done in the doc), we're having an issue when adding `showMonthAndYearPickers`.
When oppening the Picker, _**sometimes**_ the year will change to be lowered by one.
It seems it does not happens on chrome tho.

### Your Example Website or App

https://nextui.org/docs/components/date-picker#with-month-and-year-pickers

### Steps to Reproduce the Bug or Issue

Just go onto the `showMonthAndYearPickers` doc page section.

### Expected behavior

No change in the year

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/37773349/bc4e66f6-e12d-40ff-ad26-c8ae0e4728de

### Operating System Version

Windows

### Browser

Firefox

**Comment by abhinandan-verma** [comment] 2024-07-28 22:07
@RibeyrollesMatthieu  the issue is resolved in the latest version,
I believe you should close the issue.

**Closed** 2024-07-29 02:32 UTC
Labels: 🐛 Type: Bug, 📦 Scope : Components

**Comment by Sairamgene** [comment] 2024-07-30 11:40
It is also having the same issue with the Chrome Browser also the DateRange having the Previous year selecting in the year placeholder

**Comment by Sairamgene** [comment] 2024-07-30 12:13
So as for the  issue is resolved in the latest version i have upgrate to "@nextui-org/react": "^2.4.6" and "framer-motion": "^11.3.19" but still i'm facing the When oppening the Picker, sometimes the year will change to be lowered by one.
