### ISSUE TITLE
[BUG] - Production build references `process`

### ISSUE THREAD

**Issue by jdnarvaez** [nextui-org/nextui#2367] opened 2024-02-16 18:34 UTC
### NextUI Version

2.2.9

### Describe the bug

it looks like the wrapped `console.ts` utility references `process` even after a production build which results in console errors:

```typescript
// src/console.ts
var warningStack = {};
function warn(message, component, ...args) {
  var _a;
  const tag = component ? ` [${component}]` : " ";
  const log = `[Next UI]${tag}: ${message}`;
  if (typeof console === "undefined")
    return;
  if (warningStack[log])
    return;
  warningStack[log] = true;
  if (((_a = process == null ? void 0 : process.env) == null ? void 0 : _a.NODE_ENV) !== "production") {
    return console.warn(log, args);
  }
}

export {
  warn
};

```

```
chunk-RFUEKIFS.mjs:12 Uncaught ReferenceError: process is not defined
    at r_ (chunk-RFUEKIFS.mjs:12:76)
    at chunk-5U6DU2CK.mjs:56:7
    at Object.xa [as useMemo] (react-dom.production.min.js:179:119)
    at L.useMemo (react.production.min.js:25:208)
    at chunk-5U6DU2CK.mjs:34:19
    at ho (react-dom.production.min.js:167:137)
    at Pu (react-dom.production.min.js:193:57)
    at qa (react-dom.production.min.js:294:275)
    at Ga (react-dom.production.min.js:280:389)
    at Ed (react-dom.production.min.js:280:320)
r_ @ chunk-RFUEKIFS.mjs:12
(anonymous) @ chunk-5U6DU2CK.mjs:56
xa @ react-dom.production.min.js:179
L.useMemo @ react.production.min.js:25
(anonymous) @ chunk-5U6DU2CK.mjs:34
ho @ react-dom.production.min.js:167
Pu @ react-dom.production.min.js:193
qa @ react-dom.production.min.js:294
Ga @ react-dom.production.min.js:280
Ed @ react-dom.production.min.js:280
qr @ react-dom.production.min.js:280
Uu @ react-dom.production.min.js:273
vn @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
Show 14 more frames
Show less
```

### Steps to Reproduce the Bug or Issue

Trigger a warning in NextUI by supplying an invalid prop in a production build

### Expected behavior

I would expect that `process.env` would be transpiled away or conditionally chained such that it does not cause errors in the log

### Operating System Version

macOS

### Browser

Chrome

**Comment by MiloWang2048** [comment] 2024-08-14 07:16
Reproduced:

<img width="505" alt="2024-08-14 15 15 52" src="https://github.com/user-attachments/assets/d766917c-dc7d-4b46-880d-dadc1f87430c">

**Comment by jdnarvaez** [comment] 2024-08-14 14:21
@wingkwong any time there is a warning generated this happens because of the code I pasted above. 

https://github.com/nextui-org/nextui/blob/canary/packages/utilities/shared-utils/src/console.ts#L11

**Comment by wingkwong** [comment] 2024-08-14 16:23
@jdnarvaez Sorry. Can you provide detailed steps on how to reproduce the issue or even a sandbox? I still don't get how to reproduce it.

**Comment by jdnarvaez** [comment] 2024-08-14 16:26
@wingkwong you just have to have a next UI component throw a warning and it will display this error. the problem is that `process` is not defined in a browser context, so that line I linked to is invalid. Whatever bundler you are using needs to extract `process` to its appropriate transpiled variable.

**Comment by wingkwong** [comment] 2024-08-14 16:28
Can you share which components you used for producing the warning and error? Some sample code would be appreciated.

**Comment by jdnarvaez** [comment] 2024-08-14 16:30
I'll have to see if I have time outside of work to reproduce this, I cannot share anything from work that we use this library in

**Comment by jdnarvaez** [comment] 2024-08-14 16:30
I linked to the line of problematic code, `process.env` is not defined in a browser. Your bundling scheme should extract this to an injected variable, and it clearly is not doing that.

**Comment by Cyanoure** [comment] 2024-12-10 21:50
I have the same error message in `@nextui-org/react` version `2.4.8`. I'm not sure what caused it. I upgraded from `2.4.8` and I just noticed the error message in the console.

**Comment by gregmsanderson** [comment] 2024-12-13 18:55
Yep, I'm getting this error too.

`Uncaught ReferenceError: process is not defined`

As mentioned above, it's because `process` is being referenced (in the `warn()` function). In the browser that is not defined:

```
// node_modules/.pnpm/@nextui-org+shared-utils@2.1.1/node_modules/@nextui-org/shared-utils/dist/chunk-RFUEKIFS.mjs
var warningStack = {};
function warn(message, component, ...args) {
  var _a;
  const tag = component ? ` [${component}]` : " ";
  const log = `[Next UI]${tag}: ${message}`;
  if (typeof console === "undefined")
    return;
  if (warningStack[log])
    return;
  warningStack[log] = true;
  if (((_a = process == null ? void 0 : process.env) == null ? void 0 : _a.NODE_ENV) !== "production") {
    return console.warn(log, args);
  }
}
```

Where is that `warn()` called?

In my case, by simply using a `Link` component. I've tried both, with the latest version:

```
//import { Link } from "@nextui-org/link";
import { Link } from "@nextui-org/react";
```

... and both cause it.

You can confirm by looking at the NextUI demo app. That has a `NavBar` component, for example. That uses the `<Link>` component. Comment that out (so the Link is not used on the page). Sure enough, the console error goes away:

![error-is-gone](https://github.com/user-attachments/assets/a18bf37f-e32b-4bb9-9cee-aa9ae16376d2)

The `<Link>` component uses `useLink`, which in turn uses `useAriaLink`. And within that, `warn()` is called:

```
function useAriaLink(props, ref) {
  ...
  if (deprecatedOnClick && typeof deprecatedOnClick === "function") {
    warn(
      "onClick is deprecated, please use onPress instead. See: https://github.com/nextui-org/nextui/issues/4292",
      "useLink"
    );
  }
...
}
```

However the Link component is not the problem. That function will be used elsewhere too. A `warn()` wrapper is fine. It's the code _in_ the `warn()` function that needs adapting (as described above) to handle process not being defined.

**Comment by wingkwong** [comment] 2024-12-14 12:53
Fixed in https://github.com/nextui-org/nextui/pull/4327. Please wait for next version v2.6.9 or you may use canary version.

**Closed by wingkwong** 2024-12-14 12:53 UTC
Labels: 🐛 Type: Bug
