### ISSUE TITLE
[BUG] - `Button` uses deprecated `onClick` instead of `onPress`

### ISSUE THREAD

**Issue by DannyNemer** [nextui-org/nextui#482] opened 2022-05-18 18:28 UTC
### Describe the bug

Currently, the `Button` component uses the deprecated `onClick`. However, `onClick` is deprecated in favor of `onPress`, as shown in the warning below from React Dev Tools:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/170023/169117499-bf709923-2394-4ce0-b461-57adcd22c2ac.png">

### Steps to Reproduce the Bug or Issue

1. Install the Chrome extension [React Dev Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi).
2. Create a button:
    ```js
    import { Button } from "@nextui-org/react";
    
    export default function App() {
      return <Button>Hello</Button>;
    }
    ```
3. Run the `next dev` server and open `localhost:3000` in Chrome.
4. Click the button.

### Expected behavior

<img width="500" alt="image" src="https://user-images.githubusercontent.com/170023/169117499-bf709923-2394-4ce0-b461-57adcd22c2ac.png">

### Operating System Version

macOS

### Browser

Chrome

**Comment by Cow258** [comment] 2022-05-24 13:31
Are you developing React Native?

**Comment by DannyNemer** [comment] 2022-05-24 21:06
> Are you developing React Native?

@Cow258 Nope, I am only developing for React Web. Is this warning is specific to React Native?

**Comment by TechnologicNick** [comment] 2022-05-27 01:59
This is from the react-aria [`useButton` hook](https://github.com/adobe/react-spectrum/blame/1c5b08689cce962f9d9e57e01e65c76d8385c4d3/packages/%40react-aria/button/src/useButton.ts#L112). In this [blog post](https://react-spectrum.adobe.com/blog/building-a-button-part-1.html) it is explained why `onPress` has been created.

**Comment by Lantianyou** [comment] 2022-06-06 06:16
Having the same issue with React@18 web ....

**Comment by jrgarciadev** [comment] 2022-06-06 13:01
Hey guys this is not a bug, as @TechnologicNick mentioned before, the recommended way to handle the button action is using the function `onPress`,  in this blog you can find why https://react-spectrum.adobe.com/blog/building-a-button-part-1.html

**Comment by jz222** [comment] 2022-06-16 21:12
Hi,

@jrgarciadev I'm a bit confused. You mentioned that this is expected behavior and if I replace `onClick` with `onPress`, the warning indeed disappears. However, when I click the button, the warning shows up again. This can be reproduced with the latest CRA and NextUI beta 9.
I found [this](https://github.com/nextui-org/nextui/blob/main/packages/react/src/button/button.tsx#L129) line, but I'm not sure if it's actually related to this topic.

**Comment by buskerone** [comment] 2022-08-08 22:23
@jrgarciadev can we consider to re open this issue? I think we all understand that we should use `onPress` instead of `onClick` but the problem is that I'm still getting the same warning.

e.g
```typescript
<Button onPress={handleConfirm}>
...
```

**Comment by buskerone** [comment] 2022-08-11 14:28
@tianenpang any ideas on why it's showing the same warning even if I use `onPress`?

**Comment by tianenpang** [comment] 2022-08-11 21:13
Hi @buskerone the event may still handled by `onClick`, even if we passed the `onPress` prop. The `Button` also related to other components, such as `Dropdown`.

It may be necessary to refactor the integration with [`@react-aria/button`](https://react-spectrum.adobe.com/react-aria/useButton.html) 🤔

**Comment by jrgarciadev** [comment] 2022-08-30 13:34
Hey guys, this was fixed in the version `10` 🙌🏼

**Closed** 2022-08-30 13:34 UTC
Labels: bug, fixed

**Comment by KutnerUri** [comment] 2023-05-27 20:35
why actually onClick was replaced with onPress? it seems bad practice, it would make more sense to follow the standard html specification

**Comment by jrgarciadev** [comment] 2023-05-28 02:30
> why actually onClick was replaced with onPress? it seems bad practice, it would make more sense to follow the standard html specification

Hey @KutnerUri I recommend you to check these blog posts from the `react-aria` team https://react-spectrum.adobe.com/blog/building-a-button-part-1.html, "standard" HTML specifications are actually broken across platforms as Mobile devices

**Comment by ErlendKH** [comment] 2024-08-27 18:01
I'm wondering the same as [sohamnandi77](https://github.com/sohamnandi77). Also, I find that onClick works for preventing propagation, while onPress doesn't, in my use case. I have a Link parent with a button in a Popover footer, and the problem is that when clicking on the Button, the link activates, which I try to prevent... So in my use case, onPress is inferior to onClick and lacks the necessary functions.

**Comment by melodyxpot** [comment] 2024-12-25 09:41
> Hi,
> 
> @jrgarciadev I'm a bit confused. You mentioned that this is expected behavior and if I replace `onClick` with `onPress`, the warning indeed disappears. However, when I click the button, the warning shows up again. This can be reproduced with the latest CRA and NextUI beta 9. I found [this](https://github.com/nextui-org/nextui/blob/main/packages/react/src/button/button.tsx#L129) line, but I'm not sure if it's actually related to this topic.

The link you provided is not found.

**Comment by melodyxpot** [comment] 2024-12-25 09:55
> > why actually onClick was replaced with onPress? it seems bad practice, it would make more sense to follow the standard html specification
> 
> Hey @KutnerUri I recommend you to check these blog posts from the `react-aria` team https://react-spectrum.adobe.com/blog/building-a-button-part-1.html, "standard" HTML specifications are actually broken across platforms as Mobile devices

So does this mean you deprecated onClick event in your new NextUI version and preferred to use onPress for all device's best UX?

**Comment by wingkwong** [comment] 2024-12-25 10:05
@melodyxpot you may check my comment [here](https://github.com/nextui-org/nextui/issues/4292#issuecomment-2560009132).

**Comment by melodyxpot** [comment] 2024-12-25 11:56
> @melodyxpot you may check my comment [here](https://github.com/nextui-org/nextui/issues/4292#issuecomment-2560009132).

Thank you
