### ISSUE TITLE
[BUG] - Intellisense not providing auto-complete or auto-import for next-ui components

### ISSUE THREAD

**Issue by nickrupert7** [nextui-org/nextui#2657] opened 2024-04-06 22:16 UTC
### NextUI Version

2.2.10

### Describe the bug

I am no longer receiving intellisense auto-complete or auto-import suggestions for next-ui components in vscodium (telemetry-free vscode).

**Fixes I have tried:**
1. `Cmd + Shift + P` -> `Javascript: Reload Project`
2. Completely uninstall `@nextui-org/react`, remove `node_modules` folder, re-install `@nextui-org/react`
3. Add `"include": ["node_modules/@nextui-org/**/*"]` to `jsconfig.json`
4. Restart vscodium
5. Restart my computer

Note that intellisense is working for me _in general_ - that is, for all other packages I have installed in `node_modules`.

I can _manually_ type an `import` statement at the top of one of my `.jsx` React files, at which point intellisense for the imported component WILL work as expected. However, this does not help me with auto-import, which I use frequently.

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

1. Open vscodium or vscode to an existing project with React and `@nextui-org/react` installed.
2. In a React `.jsx` file, enter `<Autoc`
3. See intellisense popup. See no suggestions from `@nextui-org/react`.

### Expected behavior

Expected behavior (for example):
In a `.jsx` React file, Type `<Autoco`, then receive the suggestion to auto-complete + auto-import the `Autocomplete` component from `@nextui-org/react`.

Actual Result:
In a `.jsx` React file, Type `<Autoco`, Intellisense pop-up appears, but does not contain any suggestions from `@nextui-org/react`.

Note, this is affecting ALL next-ui components, not just Autocomplete, which I used as an example.

### Screenshots or Videos

WITHOUT Manual Import:
<img width="1440" alt="Screenshot 2024-04-06 at 5 13 41 PM" src="https://github.com/nextui-org/nextui/assets/15157368/3c631911-8777-4d8b-afa2-6b4e28418c90">

WITH Manual Import:
<img width="1440" alt="Screenshot 2024-04-06 at 5 14 02 PM" src="https://github.com/nextui-org/nextui/assets/15157368/8b6918d9-671d-44ba-92e1-5fae2db4c0f9">
<img width="1440" alt="Screenshot 2024-04-06 at 5 15 36 PM" src="https://github.com/nextui-org/nextui/assets/15157368/b23c5788-3a9d-467c-8fbe-ea624e8ab1f6">

### Operating System Version

macOS

### Browser

Other (add additonal context)

**Comment by domdevbox** [comment] 2024-04-08 13:00
Same bug here. I have tested everything but the IntelliSense auto-complete/suggestions are just not working for NextUI since yesterday.

**Comment by ananth-pranav** [comment] 2024-04-09 14:08
I have the same issue since yesterday. It was working perfectly fine and all of a sudden it stops the intellisense imports. I am not sure if it is a problem with my VSCode or NextUI. 
I also saw that ```gql``` was not being autocompleted from ```apollo/client``` either.  This gives me the confusion if the problem is with my VSCode or the packages. 

The rest of the packages imports very well.

**Comment by wingkwong** [comment] 2024-04-16 10:31
I'm using VSCode with Version: 1.88.0 (Universal) and couldn't reproduce the issue.

**Comment by domdevbox** [comment] 2024-04-16 17:09
I'm not sure how, but this is already fixed for me.

**Comment by wingkwong** [comment] 2024-05-20 11:07
Closing - since we haven't changed and it suddenly failed, then it is more on vscode side.

may refer to https://github.com/nextui-org/nextui/issues/3025 also

**Closed by wingkwong** 2024-05-20 11:07 UTC
Labels: 🐛 Type: Bug

**Comment by chavyleung** [comment] 2024-07-01 09:32
@wingkwong reproduced [here](https://stackblitz.com/~/github.com/chavyleung/my-nextui-app?file=app/page.tsx)

## Step 1

```bash
nextui init my-nextui-app
# App, my-nextui-app, pnpm

cd my-nextui-app
pnpm install

# Autocomplete suggestion is works now.
```

## Step 2

```bash
rm -rf config/
rm -rf components/
rm -rf types/
rm -rf app/about/
rm -rf app/blog/
rm -rf app/docs/
rm -rf app/pricing/
rm -rf app/error.tsx app/providers.tsx
```
 
```tsx
// app/layout.tsx
import "@/styles/globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en">
      <body>{children}</body>
    </html>
  );
}
```

```tsx
// app/page.tsx
export default function Home() {
  return (
    <>
      {/* Autocomplete suggestion fail. */}
      <Butto...
    </>
  );
}
```
