### ISSUE TITLE
[BUG] - react-hook-form

### ISSUE THREAD

**Issue by jscode28** [nextui-org/nextui#1969] opened 2023-11-14 04:54 UTC
### NextUI Version

2.2.9

### Describe the bug

`

<Input
          type="text"
          placeholder="0"
          classNames={{
            input: "text-right",
          }}
          radius="none"
          onValueChange={(value: string) => inputChange(value, "amount")}
          size="sm"
          {...register("amount", {
            required: true,
          })}
    />
`

It uses React-hook-form and next ui input, and is initialized when the value is entered with setValue.

### Steps to Reproduce the Bug or Issue

""

### Expected behavior

""

### Operating System Version

masOs

### Browser

Chrome

**Comment by jrgarciadev** [comment] 2023-11-14 12:10
Hey @jscode28 could you explain the issue a bit better? I didn't get it

**Comment by kamzata** [comment] 2023-11-14 20:08
Same here! I'm using **NextUI 2.2.9** and **RHF 7.48.2** and it's like the NextUI's input field ignores some props like `onChange`. Furthermore, NextUI's input field doesn't set the default values passed on RHF. It worked before upgrading.

**Comment by kamzata** [comment] 2023-11-15 01:45
If I replace the NextUI Input Field with a standard HTML input element it works right away.

**Comment by jrgarciadev** [comment] 2023-11-15 12:53
Did you try using this way @kamzata  https://react-hook-form.com/get-started#IntegratingwithUIlibraries ?

**Comment by kamzata** [comment] 2023-11-15 13:40
> Did you try using this way @kamzata https://react-hook-form.com/get-started#IntegratingwithUIlibraries ?

Do you mean just for testing purpose? I have a pretty complex form and I'd like to avoid replacing all the Input Fields with the Controller component.

**Comment by gustavo-gomez** [comment] 2023-11-15 14:47
> Did you try using this way @kamzata https://react-hook-form.com/get-started#IntegratingwithUIlibraries ?

I had the same issue after upgrading to the latest Nextui version.
For me works wrapping the Nextui Input inside react-hook-form Controller.

**Comment by christo9090** [comment] 2023-11-17 05:50
Agreed. Just upgraded from next ui 2.2.1 -> 2.2.9 and now none of the inputs where I was using register() from React Hook Form populate the default values. Contoller inputs still work. Downgrading for the time being and looking into what changed in Next UI's input component.

**Comment by christo9090** [comment] 2023-11-17 05:57
For debugging purposes, register from react hook form adds the following props to the input:

```
{ 
   name: 'title', 
   onChange: ƒ, 
   onBlur: ƒ, 
   ref: ƒ
}
```

**Comment by youwillbe** [comment] 2023-11-17 09:46
Same issue, `defaultValues` does not work. Now need to manually pass `defaultValue`.

**Comment by christo9090** [comment] 2023-11-17 20:16
> Same issue, `defaultValues` does not work. Now need to manually pass `defaultValue`.

Just a guess then. but if the register() function never returned a default value, I am guessing it passed it using the Ref so now somehow NextUI's update is blocking that. 

Going through the releases, the only thing that really changed with the input was updating react Aria and the Stately library was updated

**Comment by fighter3005** [comment] 2023-11-22 10:28
For me, wrapping the NextUI Input with a Controller fixes the default value problem, however, the errorMessage is not shown! The input is red, the errorMessage is passed, but it is not displayed...

**Comment by christo9090** [comment] 2023-11-22 15:02
> wrapping the NextUI Input with a Controller fixes the default value problem

> Did you try using this way

This does fix it but it sort of defeats the purpose of using react hook form and embracing uncontrolled components.

**Comment by Asamsig** [comment] 2024-01-02 19:39
Current issues that I've discovered so far, when trying to pass `{...register("field")}`:
 - No default filled values
 - Clear button in input doesn't work
 - Placeholder text doesn't change color on error
 - When clicking reset default values appear, but on hover disappear
 
Reproduction sandbox: https://codesandbox.io/p/devbox/nextui-v2-react-hook-form-forked-rm9dz8

This used to work in `@nextui-org/react@2.1.3`, as you can see in the original sandbox: https://codesandbox.io/p/devbox/nextui-v2-react-hook-form-xnwxt8
Updating to `@nextui-org/react@2.1.4` breaks the integration with react-hook-form.

I couldn't make this work in my local Next.js 14 app router project, even when downgrading to `@nextui-org/react@2.1.3`.
Reproduction sandbox Next.js 14: https://codesandbox.io/p/devbox/nextjs-nextui-react-hook-form-ck4vdj

**Comment by christo9090** [comment] 2024-01-02 19:56
> when trying to pass `{...register("field")}`

I have seen all of these same issues. I dug into this a ton before giving up and just wrapping every Input in my application with the Controller component. 

What appears to be happening is `register("field")` returns a `ref` but the ref is not applied to the input because the input ref is not exposed correctly in the new versions. I tried to manually apply it a bunch of different ways but it seems like the actual input Ref is not within the props of the Component.

**Comment by Mingyang-Li** [comment] 2024-01-04 00:12
Hey @fighter3005 , 
> For me, wrapping the NextUI Input with a Controller fixes the default value problem, however, the errorMessage is not shown! The input is red, the errorMessage is passed, but it is not displayed... I am also using RHF and Input version 2.1.16. Downgrading to Input version 2.1.9 solves the issue for now.

Have you found a way to display error messages on <Input /> components?

I'm doing the same as you (passing in error message prop), but I still couldn't display the error messages

The same is happening when I want to show error messages for the <Autocomplete /> component

**Comment by fighter3005** [comment] 2024-01-04 08:00
> Hey @fighter3005 ,
> 
> > For me, wrapping the NextUI Input with a Controller fixes the default value problem, however, the errorMessage is not shown! The input is red, the errorMessage is passed, but it is not displayed... I am also using RHF and Input version 2.1.16. Downgrading to Input version 2.1.9 solves the issue for now.
> 
> Have you found a way to display error messages on components?
> 
> I'm doing the same as you (passing in error message prop), but I still couldn't display the error messages
> 
> The same is happening when I want to show error messages for the `<Autocomplete />` component

@Mingyang-Li Are you using the older Versions (for input 2.1.9) and are you using a controller or register? Also, do you set the component as invalid (isInvalid)?

**Comment by Caperious** [comment] 2024-01-05 17:07
I also got it working using the Controller component. For anyone else needing an example, with working default values, values, and error messages, here you go: 

```ts
import { InputProps } from "@nextui-org/input/dist/input";
import { Input } from "@nextui-org/react";
import React from "react";
import { Control, Controller, FieldValue, FieldValues } from "react-hook-form";

export type FormInputProps = {
  name: string;
  control: Control<any, any>;
} & InputProps;

export const FormInput: React.FC<FormInputProps> = ({ name, ...props }) => {
  return (
    <Controller
      name={name}
      control={props.control}
      render={({ field, fieldState, formState }) => {
        return (
          <Input
            {...props}
            isInvalid={!!formState.errors?.[name]?.message}
            errorMessage={formState.errors?.[name]?.message?.toString()}
            value={field.value}
            onChange={field.onChange}
          />
        );
      }}
    ></Controller>
  );
};
```

Usage example: 
```ts
<FormInput
  name={"email"}
  label={"Email"}
  variant={"bordered"}
  control={control}
/>
```

**Comment by lanoow** [comment] 2024-01-12 09:09
> I also got it working using the Controller component. For anyone else needing an example, with working default values, values, and error messages, here you go:
> 
> ```ts
> import { InputProps } from "@nextui-org/input/dist/input";
> import { Input } from "@nextui-org/react";
> import React from "react";
> import { Control, Controller, FieldValue, FieldValues } from "react-hook-form";
> 
> export type FormInputProps = {
>   name: string;
>   control: Control<any, any>;
> } & InputProps;
> 
> export const FormInput: React.FC<FormInputProps> = ({ name, ...props }) => {
>   return (
>     <Controller
>       name={name}
>       control={props.control}
>       render={({ field, fieldState, formState }) => {
>         return (
>           <Input
>             {...props}
>             isInvalid={!!formState.errors?.[name]?.message}
>             errorMessage={formState.errors?.[name]?.message?.toString()}
>             value={field.value}
>             onChange={field.onChange}
>           />
>         );
>       }}
>     ></Controller>
>   );
> };
> ```
> 
> Usage example:
> 
> ```ts
> <FormInput
>   name={"email"}
>   label={"Email"}
>   variant={"bordered"}
>   control={control}
> />
> ```

Is the `register` function required?

**Comment by Mingyang-Li** [comment] 2024-01-16 01:54
> > Hey @fighter3005 ,
> > > For me, wrapping the NextUI Input with a Controller fixes the default value problem, however, the errorMessage is not shown! The input is red, the errorMessage is passed, but it is not displayed... I am also using RHF and Input version 2.1.16. Downgrading to Input version 2.1.9 solves the issue for now.
> > 
> > 
> > Have you found a way to display error messages on components?
> > I'm doing the same as you (passing in error message prop), but I still couldn't display the error messages
> > The same is happening when I want to show error messages for the `<Autocomplete />` component
> 
> @Mingyang-Li Are you using the older Versions (for input 2.1.9) and are you using a controller or register? Also, do you set the component as invalid (isInvalid)?

@fighter3005 Yes I have. I even set `isInvalid` hardcoded to `true` just to see if the `<Autocomplete />` component shows error messages - it doesn't make a difference

**Comment by Caperious** [comment] 2024-01-16 08:16
@Mingyang-Li Im willing to take a look, if you can provide a code sandbox example.

**Comment by Mingyang-Li** [comment] 2024-01-16 11:16
> @Mingyang-Li Im willing to take a look, if you can provide a code sandbox example.

@Caperious Thanks for the response.
You can try out my live app at https://trihard-dev.vercel.app/sessions (to create "Training Sessions" via a form)

It requires authentication, so feel free to make an account

If you're interested in the source code only, here it is: https://github.com/NorthHarbourTriathlonClub/trihard/blob/main/packages/portal/src/features/forms/create-training-session-form.tsx

**Comment by tetslee** [comment] 2024-01-24 13:28
If you have both nextui validation props (isRequired, minLength, maxLength) and RHF validation they might conflict - possibly there might be some race condition between html, nextui, and RHF validation running.

I had 2 forms that I changed to use <Controller> to get working again, but a few weeks later one of them had stopped working again while the other nearly identical one was still fine. In the one that stopped working the RHF validation doesn't seem to get triggered.

Removing the nextui validation props fixed RHF validation for me. I don't know why I had both set in the first place...

**Comment by kamami** [comment] 2024-01-25 11:52
I have also issues with RHF and NextUI Input component. I am using the latest releases of both packages. In an older project it was working as expected.

**Comment by cvolant** [comment] 2024-02-14 01:15
I just pulled my hair out for a couple of hours with this issue too...
I won't use the Controller workaround since, as @christo9090 told it before, it defeats RHF purpose...
I first tried to downgrade nextui, but it did not work. I ended up rewriting the `Input.tsx` and `Textarea.tsx` files into their uncontrolled conterparts.

**Comment by cvolant** [comment] 2024-02-14 13:00
@christo9090 

Here is my `UncontrolledTextarea.tsx` (tweaked from [NextUI `textarea.tsx`](https://github.com/nextui-org/nextui/blob/main/packages/components/input/src/textarea.tsx)):

```tsx
import { TextareaHTMLAttributes, useCallback, useMemo, useState } from 'react'

import { TextAreaProps, useInput } from '@nextui-org/react'
import { dataAttr } from '@nextui-org/shared-utils'
import { forwardRef } from '@nextui-org/system'
import { mergeProps } from '@react-aria/utils'
import TextareaAutosize from 'react-textarea-autosize'

type NativeTextareaProps = TextareaHTMLAttributes<HTMLTextAreaElement>
export type TextareaHeightChangeMeta = {
  rowHeight: number
}
type TextareaAutoSizeStyle = Omit<NonNullable<NativeTextareaProps['style']>, 'maxHeight' | 'minHeight'> & {
  height?: number
}

export const UncontrolledTextarea = forwardRef<
  'textarea',
  Omit<TextAreaProps, 'onChange'> & Pick<NativeTextareaProps, 'onChange'>
>(
  (
    {
      style,
      minRows = 3,
      maxRows = 8,
      cacheMeasurements = false,
      disableAutosize = false,
      onChange,
      onHeightChange,
      value,
      ...otherProps
    },
    ref,
  ) => {
    const {
      Component,
      label,
      description,
      startContent,
      endContent,
      hasHelper,
      shouldLabelBeOutside,
      shouldLabelBeInside,
      errorMessage,
      getBaseProps,
      getLabelProps,
      getInputProps,
      getInnerWrapperProps,
      getInputWrapperProps,
      getHelperWrapperProps,
      getDescriptionProps,
      getErrorMessageProps,
    } = useInput<HTMLTextAreaElement>({ ...otherProps, ref, isMultiline: true })

    const [hasMultipleRows, setHasMultipleRows] = useState(minRows > 1)
    const [isLimitReached, setIsLimitReached] = useState(false)
    const labelContent = label ? <label {...getLabelProps()}>{label}</label> : null

    const inputProps: NativeTextareaProps = useMemo(() => {
      const { onChange: _onChange, value: _value, ...otherInputProps } = getInputProps()
      return { onChange, value, ...otherInputProps }
    }, [getInputProps, onChange, value])

    const handleHeightChange = useCallback(
      (height: number, meta: TextareaHeightChangeMeta) => {
        if (minRows === 1) {
          setHasMultipleRows(height >= meta.rowHeight * 2)
        }
        if (maxRows > minRows) {
          const limitReached = height >= maxRows * meta.rowHeight

          setIsLimitReached(limitReached)
        }

        onHeightChange?.(height, meta)
      },
      [maxRows, minRows, onHeightChange],
    )

    const content = useMemo(
      () =>
        disableAutosize ? (
          <textarea {...inputProps} style={mergeProps(inputProps.style, style ?? {})} />
        ) : (
          <TextareaAutosize
            {...inputProps}
            cacheMeasurements={cacheMeasurements}
            data-hide-scroll={dataAttr(!isLimitReached)}
            maxRows={maxRows}
            minRows={minRows}
            style={mergeProps(inputProps.style as TextareaAutoSizeStyle, style ?? {})}
            onHeightChange={handleHeightChange}
          />
        ),
      [cacheMeasurements, disableAutosize, handleHeightChange, inputProps, isLimitReached, maxRows, minRows, style],
    )

    const innerWrapper = useMemo(() => {
      if (startContent || endContent) {
        return (
          <div {...getInnerWrapperProps()}>
            {startContent}
            {content}
            {endContent}
          </div>
        )
      }

      return <div {...getInnerWrapperProps()}>{content}</div>
    }, [startContent, endContent, getInnerWrapperProps, content])

    return (
      <Component {...getBaseProps()}>
        {shouldLabelBeOutside ? labelContent : null}
        <div {...getInputWrapperProps()} data-has-multiple-rows={dataAttr(hasMultipleRows)}>
          {shouldLabelBeInside ? labelContent : null}
          {innerWrapper}
        </div>
        {hasHelper ? (
          <div {...getHelperWrapperProps()}>
            {errorMessage ? (
              <div {...getErrorMessageProps()}>{errorMessage}</div>
            ) : description ? (
              <div {...getDescriptionProps()}>{description}</div>
            ) : null}
          </div>
        ) : null}
      </Component>
    )
  },
)

UncontrolledTextarea.displayName = 'UncontrolledTextarea'
```

It does what I need it to do, but I didn't test in in all the edge cases.
I have an `UncontrolledInput.tsx` too if you want.

**Comment by cvolant** [comment] 2024-03-02 22:48
I realized that my UncontrolledInput is pointless, because `useInput` uses `useControlledState`. It gets the input value, and this value updates `getInputProps`, so the whole component rerenders and ruins my perfs.

**Comment by AmazingTurtle** [comment] 2024-03-21 13:07
The ref to the input is not exposed. The forward ref is passed to the top most div element.

Dear maintainers, please either fix the documentation (because it no longer reflects reality):
https://nextui.org/docs/components/input#controlled
> Note: NextUI Input also supports native events like onChange, useful for form libraries such as [Formik](https://formik.org/) and [React Hook Form](https://react-hook-form.com/).

or: have it fixed so that ref is passed down again to the input.

**Comment by djyde** [comment] 2024-03-23 06:16
> The ref to the input is not exposed. The forward ref is passed to the top most div element.
> 
> Dear maintainers, please either fix the documentation (because it no longer reflects reality): https://nextui.org/docs/components/input#controlled
> 
> > Note: NextUI Input also supports native events like onChange, useful for form libraries such as [Formik](https://formik.org/) and [React Hook Form](https://react-hook-form.com/).
> 
> or: have it fixed so that ref is passed down again to the input.

It seems that currently the team is focusing on NextUI Pro. This bug had already been here long time but no one is trying to fix.

**Comment by jrgarciadev** [comment] 2024-03-24 21:16
Hey guys, thanks for sharing your issues, it seems the `ref` is working properly in the `Input` component therefore the `defaultValues` are not working, as a workaround please use the `Controller` component from `react-hook-form` here's an example:

https://stackblitz.com/edit/vitejs-vite-xdeajz?file=src%2FApp.tsx

**Comment by christo9090** [comment] 2024-03-25 14:51
> it seems the `ref` is not working properly in the `Input` component therefore the `defaultValues` are not working

Thanks for looking into this @jrgarciadev. Is the ref issue going to be addressed in a future update? The workaround does work, and I implemented it throughout my app a while ago. However, the reason React Hook Form uses the ref is to prevent unnecessary re-renders. So the workaround isn't a 1 for 1 fix. I think that's what most of us are alluding to in this thread.

**Comment by notmedia** [comment] 2024-03-25 15:53
> > it seems the `ref` is not working properly in the `Input` component therefore the `defaultValues` are not working
> 
> Thanks for looking into this @jrgarciadev. Is the ref issue going to be addressed in a future update? The workaround does work, and I implemented it throughout my app a while ago. However, the reason React Hook Form uses the ref is to prevent unnecessary re-renders. So the workaround isn't a 1 for 1 fix. I think that's what most of us are alluding to in this thread.

Instead of `as` prop use `render` in Controller to extract ref

**Closed** 2024-04-16 12:25 UTC
Labels: bug

**Comment by christo9090** [comment] 2024-04-29 16:34
Can confirm this works. Thanks for fixing.

**Comment by jimhdev** [comment] 2024-07-12 00:23
Still issues for me

**Asynchronous** default values are disappearing from <Input> on hover. Issue doesn't occur on plain <input> tags. Wrapping in a <Controller/> doesn't fix.

Next 14.2.4
NextUI 2.4.2
React-Hook-Form 7.52.1

**Comment by wingkwong** [comment] 2024-07-12 02:16
@jimhdev please create a new issue with a minimal reproducible example.

**Comment by jimhdev** [comment] 2024-07-12 21:34
> @jimhdev please create a new issue with a minimal reproducible example.

Apologies, I had screwed up the controlled version. The phenomenon of an async default value disappearing on hover does occur for a directly registered NextUI `<Input>` component if it's not wrapped in React-Form-Hook's <Controller/> component, but if it is, the behaviour isn't observed.

As React-Hook-Form advise using `<Controller/>` on external UI libraries I would say this is a non-issue.
