### ISSUE TITLE
[BUG] - Nextui tooltip error

### ISSUE THREAD

**Issue by treconyl** [nextui-org/nextui#2515] opened 2024-03-13 16:29 UTC
### NextUI Version

2.0.10

### Describe the bug

<Tooltip content="Total number of operating days">
                  <Button variant="flat" className="border rounded-xl px-4 py-2 text-gray-900 flex space-x-2 justify-center items-center">
                    content
                  </Button>
                </Tooltip>
When moving or doing nothing it will display the following error message:
Error: Only two keyframes currently supported with spring and inertia animations. Trying to animate scale(0.6),scale(0.61547),scale(0.65082),scale(0.69443),scale(0.73944),scale(0.78204),scale(0.82036),scale(0.85368),scale(0.88195),scale(0.90551),scale(0.92487),scale(0.94061),scale(0.95328),scale(0.9634),scale(0.97144),scale(0.97779),scale(0.98278),scale(0.98668),scale(0.98973),scale(0.99209),scale(0.99393),scale(0.99534),scale(0.99644),scale(0.99728),scale(0.99792),scale(0.99842),scale(0.99879),scale(0.99908),scale(0.9993),scale(0.99947),scale(1)

### Steps to Reproduce the Bug or Issue

Move between two Tooltip blocks quickly or do nothing

### Expected behavior

Fix this bug in the next update

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/75132211/a57a86e8-20fd-4ee7-9426-1472ef9cf4db)

https://github.com/nextui-org/nextui/assets/75132211/8131af32-c5fe-4f89-9797-4c1f64506a62

### Operating System Version

Window 11 Home

### Browser

Chrome

**Comment by alphaxek** [comment] 2024-03-13 18:12
Hi @aryanranderiya @treconyl, whats the `framer-motion` version you have, and have you put any other `framer-motion` animations on top of it?

Seems to be working fine in docs
https://nextui.org/docs/components/tooltip

![multipleTooltip](https://github.com/nextui-org/nextui/assets/116849110/a0623ea2-8eca-4bbe-8f73-a5189863f8ad)

**Comment by aryanranderiya** [comment] 2024-03-13 19:52
i'm using the version 11.0.12 of framer-motion.

this is my code:

> Login.jsx 
```
import * as React from "react";
import LoginInputs from "../components/LoginInputComponent";
import SelectComponent from "../components/SelectComponent";

export default function Login() {
  return (
    <>
      <main className="dark text-foreground bg-background text-center flex justify-center gap-4 h-screen items-center flex-col">
        <SelectComponent />
        <LoginInputs />
      </main>
    </>
  );
}

```

> SelectComponent.jsx
```
import { Select, SelectItem } from "@nextui-org/react";
export default function SelectComponent() {
  const loginTypes = [
    { label: "Faculty", value: "Faculty" },
    { label: "Head of Department", value: "HOD" },
    { label: "Director", value: "Director" },
  ];

  return (
    <>
      <Select
        label="Role"
        placeholder="Select Role"
        className="max-w-xs select-input"
        value="Faculty"
        isRequired={"true"}
        defaultSelectedKeys={["Faculty"]}
        variant="faded"
      >
        {loginTypes.map((loginType) => (
          <SelectItem key={loginType.value} value={loginType.value}>
            {loginType.label}
          </SelectItem>
        ))}
      </Select>
    </>
  );
}

```

> tailwind.config.js
```
/** @type {import('tailwindcss').Config} */

const { nextui } = require("@nextui-org/react");

module.exports = {
  content: [
    "./src/**/*.{html,js}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  darkMode: "class",
  plugins: [nextui()],
};
```

When I try to open and close the select widget it throws an error. Tried this in 2 different projects too and different widgets too. Maybe I'm installing it incorrectly or?

> Preview:

![chrome_9bY6e3NNT7](https://github.com/nextui-org/nextui/assets/64796509/9d3be18c-f27f-47da-a0ee-ee20482e6e1a)

It works fine until I double click on it

**Comment by MorkWood2** [comment] 2024-03-13 19:57
Running into the same problem

**Comment by Luna-devv** [comment] 2024-03-13 20:00
Having the same issue

**Comment by alphaxek** [comment] 2024-03-13 20:55
@aryanranderiya thanks for the code. I tried locally, seems to be working fine.
can you try this version `"framer-motion": "10.12.16"`

Test:
![test1](https://github.com/nextui-org/nextui/assets/116849110/2c7eb0fe-f0c8-4592-8fdc-bf2985a89300)

**Comment by aryanranderiya** [comment] 2024-03-13 20:57
Could you try double clicking on it because that's where the issue is occuring? like double click on this:

![image](https://github.com/nextui-org/nextui/assets/64796509/90889505-1687-493c-8cd0-99cfdbe850b4)

**Comment by utkubiz** [comment] 2024-03-14 07:50
I had same issue with framer-motion 11.0.12. I have downgraded to 10.12.16. now its working.

**Comment by J4v4Scr1pt** [comment] 2024-03-14 10:40
I also just ran in to this issue upgrading FM from 11.0.8 to 11.0.12. I have been using v.11 a looong time(since Jan 21) and it had always worked.
Tried downgrading minor version by version.. nothing worked until I got till v.10.x.x.. I was super confused.. then realised I had the ^ before the version. Set it hard 11.0.8 and it works. Something in version .12 that has issues.

**Comment by J4v4Scr1pt** [comment] 2024-03-14 10:49
> Yes, I downgraded framer-motion from 11 to 10.12.16 which worked fine, seems version 11 is having problems

11.0.8 work for me, it's something in the minor version 12

**Comment by alphaxek** [comment] 2024-03-14 21:08
Hi @aryanranderiya, if your query is resolved, please mark my above msg as answered, will really appreciate. thanks!

**Comment by alphaxek** [comment] 2024-03-14 22:12
Hi @treconyl, if your query is resolved, please close this issue, will appreciate, thanks!

**Closed** 2024-03-17 15:21 UTC
Labels: bug

**Comment by danverbs** [comment] 2024-03-18 11:01
Issue is still present in v11.0.13

**Comment by J4v4Scr1pt** [comment] 2024-03-18 11:59
> Issue is still present in v11.0.13

Ahh ok, thx for the info. Wonder if its NextUI or FM that has the issue. Guess we will find out when NextUI update their package :)

**Comment by alphaxek** [comment] 2024-03-24 19:32
> I'm using
> 
> ```
> "@nextui-org/react": "^2.2.10",
> "framer-motion": "^11.0.18"
> ```
> 
> still got the issue, yeah we supposed to wait for the update 😄

@LangRizkie Meanwhile have a look at this `package.json` from latest NextUI docs

https://codesandbox.io/p/devbox/infallible-chebyshev-f5v48f?file=%2Fpackage.json%3A10%2C33&utm_medium=sandpack

**Comment by J4v4Scr1pt** [comment] 2024-04-05 06:24
v.11.0.24 working
