### ISSUE TITLE
[BUG] - Framer Motion ^11 "Error: Only two keyframes currently supported with spring and inertia animations" on Popover and Select

### ISSUE THREAD

**Issue by isaackoz** [nextui-org/nextui#2519] opened 2024-03-14 06:03 UTC
### NextUI Version

2.2.9

### Describe the bug

When using Framer Motion 11, if you open and close a Popover quickly (before the animation ends), the following error gets thrown:

`
Error: Only two keyframes currently supported with spring and inertia animations. Trying to animate scale(0.8),scale(0.80774),scale(0.82541),scale(0.84721),scale(0.86972),scale(0.89102),scale(0.91018),scale(0.92684),scale(0.94097),scale(0.95275),scale(0.96244),scale(0.9703),scale(0.97664),scale(0.9817),scale(0.98572),scale(0.9889),scale(0.99139),scale(0.99334),scale(0.99486),scale(0.99605),scale(0.99696),scale(0.99767),scale(0.99822),scale(0.99864),scale(0.99896),scale(0.99921),scale(0.9994),scale(0.99954),scale(0.99965),scale(0.99974),scale(1)`

This is likely due to the following: https://github.com/framer/motion/issues/2190#issuecomment-1878437924
> Spring/inertia has never worked with multiple keyframes (you can see in the working animation the animation settings aren't actually taking effect). Adding this support is unlikely but I can make a better error message.

The error will only be thrown in a dev environment and was introduced here framer/motion#2474. I have only tested this on the Select and Popover components and can confirm both throw the same error.

### Steps to Reproduce the Bug or Issue

1. Use either a popover or select component
```jsx
import {Popover, PopoverTrigger, PopoverContent} from "@nextui-org/react";
//...
<Popover>
    <PopoverTrigger>Hello</PopoverTrigger>
    <PopoverContent>
        <div>World</div>
    </PopoverContent>
</Popover>
```
2. Click the trigger very quickly, before the animation finishes

### Expected behavior

I expect the popover to be able to open and close quickly, without error. 

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment] 2024-03-14 07:58
duplicate of #2515. A temporary workaround is to use `10.12.16` as mentioned in the linked issue.

**Comment by baijunjie** [comment] 2024-03-24 05:23
same issue

**Comment by baijunjie** [comment] 2024-03-24 07:30
> Could you check the version in the lock file? (Or in node_modules?). It could not be downgraded to `v10.12.16`.

Yeah, it doesn't seem to collapse anymore.

**Comment by wingkwong** [comment] 2024-03-27 04:36
Seems framer motion team have made the fix. Please try `framer-motion@11.0.22`. Remember to remove `node_modules` first.

**Comment by Nickman87** [comment] 2024-04-05 17:38
> Seems framer motion team have made the fix. Please try `framer-motion@11.0.22`. Remember to remove `node_modules` first.

I just tried with the new version and it seems to have stabilised now, thanks!

**Closed** 2024-04-06 05:45 UTC
Labels: bug
