### ISSUE TITLE
[BUG] - Console errors out when typing in autocomplete component

### ISSUE THREAD

**Issue by srivatsa17** [nextui-org/nextui#2074] opened 2023-11-30 16:03 UTC
### NextUI Version

2.2.9

### Describe the bug

Typing in the Autocomplete component errors out on console with message `stopPropagation is now the default behavior for events in React Spectrum. You can use continuePropagation() to revert this behavior.`

### Steps to Reproduce the Bug or Issue

1. Write a simple autocomplete component and try to write on the input field
2. Console will error out with the above mentioned issue.

### Expected behavior

No errors should be logged to the console. 
Also i see that the bug is fixed in this https://github.com/adobe/react-spectrum/issues/2263. Maybe upgrading react-spectrum may solve this issue.

### Screenshots or Videos

<img width="755" alt="image" src="https://github.com/nextui-org/nextui/assets/52497355/9cddaeec-19bb-416b-9891-81524301c1f2">

### Operating System Version

macOS

### Browser

Firefox

**Comment by wehrhaus** [comment] 2023-11-30 23:53
I'm encountering the same issue. I've got a thread going in the discord channel: https://discord.com/channels/856545348885676062/1179925079447056394

**Comment by E-Naeim** [comment] 2023-12-04 11:48
I have the same issue

**Comment by NiiightmareXD** [comment] 2023-12-04 18:41
I have the same issue

**Comment by ekajaya740** [comment] 2023-12-05 14:41
I have the same issue

**Comment by black197** [comment] 2023-12-06 08:44
seems like duplicate of #1909

**Comment by ModzabazeR** [comment] 2023-12-24 16:20
I have the same issue

**Comment by amirstepT** [comment] 2024-01-08 00:39
Putting this in my `<Autocomplete>` solved the problem.  Don't ask me how but it solved it.

`onKeyDown={(e) => e.continuePropagation()}`

**Comment by AirP0WeR** [comment] 2024-01-15 14:01
Same bug to me.

**Comment by NiroopR1999** [comment] 2024-01-18 02:06
> Putting this in my `<Autocomplete>` solved the problem. Don't ask me how but it solved it.
> 
> `onKeyDown={(e) => e.continuePropagation()}`

This indeed solved the solved the problem thank you.

**Comment by amirstepT** [comment] 2024-02-04 14:36
> Same bug to me. @amirstepT solution help me. But I gott Erron in VScode ![image](https://private-user-images.githubusercontent.com/3369032/296776728-9683f4c1-99a7-4680-a00f-68e608364f56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNTc2MDUsIm5iZiI6MTcwNzA1NzMwNSwicGF0aCI6Ii8zMzY5MDMyLzI5Njc3NjcyOC05NjgzZjRjMS05OWE3LTQ2ODAtYTAwZi02OGU2MDgzNjRmNTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDRUMTQzNTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTkyZWUwYmI0NGI3NTY4ZWI5Y2FlYzVjMzBkNTc2NmJlY2UyMTBjZDlmMWQ4M2I0NjcwYWMyYjdkMTI5ZGI0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZhSAUVhRPKdVMDtE2EGl0goVlKFQ2Aas_0KJV2rfn80)

The error is a typescript error that can be fixed if you do this:

`onKeyDown={(e: any) => e.continuePropagation()}`

**Comment by manuel-mauky** [comment] 2024-03-13 16:35
I get the same error message with the `<Dropdown>` when I'm trying to use a custom component as `<DropdownTrigger>`.
See this [code example](https://codesandbox.io/p/devbox/nextui-custom-dropdown-trigger-forked-t35jyg?workspaceId=dd234978-1edd-4189-9bf6-6355d2e37c45&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltfxlukb00052e654fdks64g%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltfxlukb00022e65xldoj4sz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltfxlukb00032e65guqf9aut%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltfxlukb00042e654l8esw9u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B62.24201489509706%252C37.75798510490294%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltfxlukb00022e65xldoj4sz%2522%253A%257B%2522id%2522%253A%2522cltfxlukb00022e65xldoj4sz%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltq0fr9j00022e67gr89e1sm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltq0fr9j00022e67gr89e1sm%2522%257D%252C%2522cltfxlukb00042e654l8esw9u%2522%253A%257B%2522id%2522%253A%2522cltfxlukb00042e654l8esw9u%2522%252C%2522activeTabId%2522%253A%2522cltfxmku3006b2e65pjb0m13s%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522cltfxmku3006b2e65pjb0m13s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cltfxlukb00032e65guqf9aut%2522%253A%257B%2522id%2522%253A%2522cltfxlukb00032e65guqf9aut%2522%252C%2522activeTabId%2522%253A%2522cltfxmgo8004p2e65d5f4ect7%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cltfxmgo8004p2e65d5f4ect7%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A11.46778042959427%257D). This is based on [this issue](https://github.com/nextui-org/nextui/issues/1516#issuecomment-1697015691) with the only difference that I'm using `<Button>` instead of `<button>`.
Now, when you navigate to the button via keyboard (tab) and press `Enter` the same warning appears.

For the `<DropdownTrigger>`/`<Dropdown>` the trick with `continuePropagation` does not work due to `e.continuePropagation is not a function` (so it's not TypeScript issue but an exception at runtime).

It seems to be related as it's the same error message but I can also create a separate bug ticket?

**Comment by henry-ppoint** [comment] 2024-04-12 06:14
solved it. thank you.
Another way in typescript.
```
onKeyDown={(e) => {
  if ("continuePropagation" in e) {
    e.continuePropagation()
  }
}}
```

**Comment by jacknie84** [comment] 2024-04-12 06:15
solved it. thank you.
Another way in typescript.
```
onKeyDown={(e) => {
  if ("continuePropagation" in e) {
    e.continuePropagation()
  }
}}
```

**Closed** 2024-06-07 11:51 UTC
Labels: 🐛 Type: Bug
