### ISSUE TITLE
[BUG] - Dropdown Menu turns off automatically

### ISSUE THREAD

**Issue by fundon** [nextui-org/nextui#649] opened 2022-07-31 10:20 UTC
### Describe the bug

The dropdown menu is not behaving correctly, it opens and closes automatically.

### Steps to Reproduce the Bug or Issue

1. Open the https://nextui.org/.
2. click the dropdown button.

### Expected behavior

Click the button then open the dropdown menu.

### Screenshots or Videos

https://user-images.githubusercontent.com/27926/182021621-dae2f214-e4f6-4f89-b6e3-49d54374dff4.mov

### Operating System Version

macOS

### Browser

Firefox/Chrome

**Comment by ahmad1702** [comment] 2022-08-01 03:49
I second this. I tested this on Windows, Mac, and Linux. The issue does not happen on IOS safari though, just web apps.

**Comment by fundon** [comment] 2022-08-01 04:09
I tested on macOS, Firefox, Chrome, Safari, doesn't work properly on all three browsers.

But popover works right. 🤔

**Comment by Ryannnkl** [comment] 2022-08-01 13:42
https://user-images.githubusercontent.com/48577990/182159517-1d6890f9-8b22-4bb1-a321-09c473b26add.mp4

does it work like this?
* when the dropdown appeared it was because I held down the mouse button.
> but last time it showed up because i just clicked

**Comment by znareak** [comment] 2022-08-01 16:48
I have the same problem :(

**Comment by fundon** [comment] 2022-08-01 19:52
> does it work like this?

Right, not consistent with expected behavior.

The correct behavior is to click once, release the mouse and then pop up the menu.

**Comment by aaaravv** [comment] 2022-08-02 13:58
Yeah i also faced the issue, but Dropdown works fine in smaller widths & browser's responsive view.

**Comment by jrgarciadev** [comment] 2022-08-03 02:04
Hi guys, could you please try again? 🙌🏻

**Comment by fundon** [comment] 2022-08-03 06:41
Its working. 

How to fix that?

**Comment by jrgarciadev** [comment] 2022-08-03 13:29
It was a cache issue in the docs app deployment, It was not a Dropdown issue 👍🏻

**Comment by ahmad1702** [comment] 2022-08-03 16:41
Its working now, great job guys, love the work you guys have been doing so far

**Comment by aaaravv** [comment] 2022-08-04 02:25
How to fix the issue, I am using Dropdown in production build and tried deploying several times since the issue has been closed.

**Comment by fundon** [comment] 2022-08-04 03:19
But in my local environment, the problem has always been there, whether in development mode or production mode.

**Comment by aaaravv** [comment] 2022-08-04 03:49
> But in my local environment, the problem has always been there, whether in development mode or production mode.

It's strange I didn't faced the issue locally at all Only in production build.

**Comment by tianenpang** [comment] 2022-08-04 12:42
Hi @aaaravv @fundon could you please share a full repro case?

**Comment by fundon** [comment] 2022-08-04 13:39
Hi @tianenpang, I creates a small case https://github.com/fundon/yarn-npm-test.

When building with yarn, the above problem is encountered.

1. yarn, the issue happens

```console
yarn
yarn start
```

3. npm, it's fine

```console
git checkout npm
npm i
npm start
```

**Comment by tianenpang** [comment] 2022-08-04 14:44
@fundon thank you for the repro, I'm able to reproduce the issue with `yarn` 🤔

**Comment by fundon** [comment] 2022-08-04 14:52
You can remove the yarn-lock file,   Try again.

**Comment by aaaravv** [comment] 2022-08-04 18:17
> Hi @tianenpang @aaaravv, I created a small case https://github.com/fundon/yarn-npm-test.
> 
> When building with yarn, the above problem is encountered.
> 
>     1. yarn, the issue happens
> 
> 
> ```
> yarn
> yarn start
> ```
> 
>     2. npm, it's fine
> 
> 
> ```
> git checkout npm
> npm i
> npm start
> ```

Hey @fundon @tianenpang exactly the issue occurs only when

> Installing and building package via yarn

```console
yarn install
yarn run build
serve -s build
```

Tried locally via npm it's working fine but on deploying production build upon Vercel via yarn this issue can be reproduced.

**Comment by hectormanueljsx** [comment] 2022-08-04 19:49
Hello, I am using the library, but it shows the following warning, when the dropdown is pressed it has strange behavior

![image](https://user-images.githubusercontent.com/101850484/182939589-8b01bac6-cb41-4f23-9a67-8ea7c996e47f.png)

**Comment by neelspansare** [comment] 2022-08-05 11:10
It's still happening on my local server. I am using  "@nextui-org/react": "^1.0.0-beta.9"

https://user-images.githubusercontent.com/71687022/183065630-43b4f2bd-fdd7-4f80-ad84-03d1cfc634e4.mov

**Comment by mikael1995** [comment] 2022-08-05 20:55
> Выпадающий список мерцает для меня, это все еще происходит на моем локальном сервере. Я использую "@nextui-org/react": "^1.0.0-beta.9"
> 
>  Экран.Запись.2022-08-05.в.4.31.56.PM.mov

I have same problem... what is the reason ?((

**Comment by buskerone** [comment] 2022-08-06 02:47
Same issue here, but I can't see it happening in the example of the official docs.

**Comment by mikael1995** [comment] 2022-08-06 09:24
[ice_video_20220806-114625.webm](https://user-images.githubusercontent.com/27006220/183243095-57e18e29-277d-4555-a981-773c3cc29324.webm)

**Comment by tianenpang** [comment] 2022-08-06 14:24
Hi guys, thanks for the feedback.

For the warning that `onClick is deprecated, please use onPress` it may be related to the `Button`.
- https://github.com/nextui-org/nextui/issues/482

For the flickering issue please try to downgrade `react` and `react-dom` to `17.0.2`.
- https://github.com/nextui-org/nextui/discussions/565

*It would be better to create different issues* 🙌🏻

**Comment by mikael1995** [comment] 2022-08-06 16:29
will there be animation support for version 18?

**Comment by buskerone** [comment] 2022-08-07 23:43
> * [BUG] - `Button` uses deprecated `onClick` instead of `onPress` #482

Regarding the main issue that @fundon reported, I already tried to downgrade `react` and `react-dom` to `17.0.2` but no luck at all, the problem persist. The animation glitch disappears, but this doesn't fix the bug reported in this thread.

**Comment by JabirDev** [comment] 2022-08-08 00:33
> Regarding the main issue that @fundon reported, I already tried to downgrade `react` and `react-dom` to `17.0.2` but no luck at all, the problem persist. The animation glitch disappears, but this doesn't fix the bug reported in this thread.

1. Remove the `node_modules` folder
2. Install using `npm install`

**Comment by lqd1434** [comment] 2022-08-09 16:17
I have the same problem, and when I change the trigger to "longPress" ,it work fine, it is so strange, haha.

**Comment by buskerone** [comment] 2022-08-09 16:26
> > Regarding the main issue that @fundon reported, I already tried to downgrade `react` and `react-dom` to `17.0.2` but no luck at all, the problem persist. The animation glitch disappears, but this doesn't fix the bug reported in this thread.
> 
> 1. Remove the `node_modules` folder
> 2. Install using `npm install`

it's not an option for our team to use npm. :( do you know exactly why does it work with npm instead of yarn?

**Comment by tianenpang** [comment] 2022-08-09 17:10
Hi all, I'm still looking for this strange issue, currently using `npm` or [`pnpm`](https://pnpm.io/) will work as expected.

Hey @buskerone The `Dropdown` in the docs works is because the `@nextui-org/react` is compiled and imported directly from the `packages/react` in monorepo.

The issue is only with `yarn add` 🤔

**Comment by buskerone** [comment] 2022-08-09 18:31
@tianenpang thank you! you're right! I'll try to do some research to understand why it's not working with `yarn`

**Comment by ibrahimhozhun** [comment] 2022-08-13 13:11
> I have the same problem, and when I change the trigger to "longPress" ,it work fine, it is so strange, haha.

I tried that and it still flickers but just once then it stays open as it should be

**Comment by andrew-t-james** [comment] 2022-08-13 13:25
+1 same issue when using `yarn` or `npm`.

**Comment by buskerone** [comment] 2022-08-19 13:28
This is one of the issues with more comments/activity + it's related to a new component, thus we should give some sort of priority to it. It doesn't seems to work with `yarn` or `npm`, and checking the source code I can't find the issue.

If someone has an idea of what's the main issue and some guidelines on how to fix it, I'll be more than happy to help with it.

**Comment by buskerone** [comment] 2022-08-21 16:44
I've found something that may help:

We already know that when doing a long press the dropdown is visible, but if you do a long press on the `Dropdown.Button`, then move your mouse (without releasing your mouse) outside the button and finally releasing it, you'll see the that the `Dropdown.Menu` stays visible. I've seen that `Dropdown.Button` is being wrapped by `DropdownTrigger `, but I'm not sure how everything is being handled with `onPress, onPressStart, onPressEnd, onPressChange, onPressUp`.

Any thoughts on this @jrgarciadev ?

https://user-images.githubusercontent.com/2034112/185801592-b50108c6-e726-47b8-8f94-63b09edbca99.mov

**Comment by buskerone** [comment] 2022-08-26 20:05
It's working good now with `v1.0.0-beta.10` ❤️ !

**Comment by mikael1995** [comment] 2022-08-26 20:54
> ice_video_20220806-114625.webm

It still dont work in beta 10((( i get same result

**Comment by jrgarciadev** [comment] 2022-08-30 13:36
Hey guys, could you try this again using the latest version (v10) and react 17?

**Comment by fundon** [comment] 2022-08-31 12:54
react 18 + nextui  v10, its working now.

**Comment by indiemakersid** [comment] 2022-09-15 03:55
Hey it's still persist here. 
I am using these.

```json
"@nextui-org/react": "^1.0.0-beta.10",
"next": "12.3.0",
"react": "18.2.0",
"react-dom": "18.2.0",
"recoil": "^0.7.5"
```

**Comment by BlackSenPig** [comment] 2022-09-25 11:50
I faced the same issue with popover in chrome and firefox.



https://user-images.githubusercontent.com/16597753/192141829-e6fa2b0a-b833-48bd-a82d-0cefce28e4dc.mov

**Comment by zvictor** [comment] 2022-12-23 02:22
I only have issues while using iOS.
Clicking on the dropdown button does nothing. Not even in the official docs it works.

It's such a critical bug that I think the Dropdown component should be temporarily hidden in the docs, so we don't have more people getting fired for adding broken UI in production 😅

https://user-images.githubusercontent.com/181076/209258120-72ec7ee1-9df1-4177-b81e-f89a799866ab.MP4

**Comment by tianenpang** [comment] 2022-12-23 12:10
Hey @buskerone I noticed that behavior too but the current behavior is the same as [`@react-aria/menu`](https://react-spectrum.adobe.com/react-aria/useMenu.html).

Different trigger behavior than `Popover`, `Dropdown`'s interaction occurs when `onPressStart`.

**Comment by mikelxc** [comment] 2023-01-02 20:38
Found out what might cause the issue with yarn. 
In yarn.lock when ^1.0.0-beta.11 is specified:
@nextui-org/react@npm:^1.0.0-beta.11":
  version: 1.0.0-beta.9-dbg2
  resolution: "@nextui-org/react@npm:1.0.0-beta.9-dbg2"
It seems yarn thinks 1.0.0-beta.9-dbg2 is newer than 1.0.0-beta.11 and installed it instead, same behavior for @latest
Using "@nextui-org/react":1.0.0-beta.11 in pakcage.json solved the problem for me.

**Comment by jrgarciadev** [comment] 2023-01-03 19:06
I'll close this issue in favor of this one: https://github.com/nextui-org/nextui/issues/969

**Closed by jrgarciadev** 2023-01-03 19:06 UTC
Labels: bug, pending release, fixed
