### ISSUE TITLE
[BUG] - In Select Component need a   props "allowClear"  

### ISSUE THREAD

**Issue by Arjun059** [nextui-org/nextui#2687] opened 2024-04-11 14:41 UTC
### NextUI Version

2.x.x

### Describe the bug

I don't want to user to clear selected item. need allowClear props.  ref https://ant.design/components/select

### Steps to Reproduce the Bug or Issue

I don't want to user to clear selected item.

### Expected behavior

I don't want to user to clear selected item. need allowClear props. ref https://ant.design/components/select 

### Screenshots or Videos

I don't want to user to clear selected item.  ref https://ant.design/components/select

### Operating System Version

Window

### Browser

Chrome

**Comment by wingkwong** [comment] 2024-04-12 10:41
Closing - duplicate of #1579

**Closed by wingkwong** 2024-04-12 10:41 UTC
Labels: bug
