### ISSUE TITLE
[BUG] - Textarea minRows - height bug

### ISSUE THREAD

**Issue by Arrugonoto** [nextui-org/nextui#3422] opened 2024-07-06 20:40 UTC
### NextUI Version

2.4.2

### Describe the bug

While setting **minRows** prop of Texrarea component with value as '1' the initially rendered height of component is displayed as height of 3 rows.
Initially component renders with style for height as '60px !important', but after receiving focus or hover it shrinks to '20px !important'. Happens on Firefox and Chrome (selector in ticket allows to select only one browser).

Setting inline styling, adding id, custom class etc. with '!important' declaration doesn't works, it instantly gets overwritten by build in styling for component.
Note: I want to maintain auto size functionality, so answer with 'disableautoSize' won't help.

### Steps to Reproduce the Bug or Issue

1. Import Textarea component
2. Set prop **minRows={1}**

```jsx
<Textarea
          aria-label="Message"
          id="textarea-height"
          isRequired={!prompt}
          size="sm"
          radius="full"
          type="text"
          name="message"
          placeholder="Question"
          value={prompt}
          onChange={(e) => handlechange(e)}
          minRows={1}
          maxRows={3}
          className="w-full p-0"
          classNames={{
            inputWrapper: [
              'bg-content3',
              'group-data-[focus=true]:bg-content1',
            ],
          }}
        />
 ```

### Expected behavior

While setting minRows={1} the component should render with height for 1 row, instead renders with height for 3 rows and shrinks after focus or hover.

### Operating System Version

Windows[11]

### Browser

Chrome

**Comment by ryo-manba** [comment] 2024-07-09 12:18
I couldn't reproduce the issue. Could you provide a minimal reproducible example on Stackblitz? 
Also, could you try with the latest version?

**Comment by Arrugonoto** [comment] 2024-07-10 17:15
I was able to reproduce issue.

In the end it wasn't the issue of NextUI Component, but adding max width(or width) property for container.

While container have max width(or width) set as smaller value than is minimally required by **Textarea** component, the component initially renders wrapped(like wrap or flexwrap property) with greater height and didn't return to standard height until receives focus or hover status. Issue resolves while width of container is enough to contain minimum width of **Textarea** component. 

So to reproduce:
1. Set initial height / max-height of container as 100px
2. Conditionally render container with **Textarea**
3. Set rendered conditionally container width for i. e. 500px with transition, after [true]
4. Container width changed but Textarea height stays as height of 3 rows even despite setting value of minRows={1} until focus, active or hover state happened on component

**Comment by Arrugonoto** [comment] 2024-07-10 17:27
> I was able to debug the issue.
> 
> In the end it wasn't the issue of NextUI Component, but adding max width(or width) property for container.
> 
> While container have max width(or width) set as smaller value than is minimally required by **Textarea** component, the component initially renders wrapped(like wrap or flexwrap property) with greater height and didn't return to standard height until receives focus or hover status. Issue resolves while width of container is enough to contain minimum width of **Textarea** component.
> 
> So to reproduce:
> 
>     1. Set initial height / max-height of container as 100px
> 
>     2. Conditionally render container with **Textarea**
> 
>     3. Set rendered conditionally container width for i. e. 500px with transition, after [true]
> 
>     4. Container width changed but Textarea height stays as height of 3 rows even despite setting value of minRows={1} until focus, active or hover state happened on component

To fix that issue, wrap Textarea in another div with **[min-width: 200px]** and delay render of wrapper

**Comment by ryo-manba** [comment] 2024-07-11 22:50
Glad to hear that the issue seems to be resolve. I will close this issue.
If you encounter any other problems, please feel free to open a new issue.

**Closed by ryo-manba** 2024-07-11 22:50 UTC
Labels: 🐛 Type: Bug, 🔎 Status: More Info Needed
