### ISSUE TITLE
[BUG] - Using Datepicker is broken when showMonthAndYearPicker=true and maxValue is set to todays date

### ISSUE THREAD

**Issue by henry-hein** [nextui-org/nextui#3839] opened 2024-10-03 13:49 UTC
### NextUI Version

"@nextui-org/react": "^2.4.6"

### Describe the bug

This is my current setup. please see video for better explanation

import { CalendarDate, DateFormatter, getLocalTimeZone, today } from '@internationalized/date';

 const [startDate, setStartDate] = useState<CalendarDate | null>(null);
 const maxDate = today(getLocalTimeZone());
 
 <DatePicker
            label="From Date"
            value={startDate}
            onChange={setStartDate}
            showMonthAndYearPickers
            granularity='day'
            maxValue={maxDate}
            className="w-full"
            calendarProps={{ color: 'danger' }}
          />
 
https://github.com/user-attachments/assets/146caefd-7cea-4c54-8be9-3ef47a5e3d73

### Steps to Reproduce the Bug or Issue

1. Use datepicker with showMonthAndYearPicker=true and maxValue is set to todays date.

 const [startDate, setStartDate] = useState<CalendarDate | null>(null);
 const maxDate = today(getLocalTimeZone());
 
 <DatePicker
            label="From Date"
            value={startDate}
            onChange={setStartDate}
            showMonthAndYearPickers
            granularity='day'
            maxValue={maxDate}
            className="w-full"
            calendarProps={{ color: 'danger' }}
          />
          
2. click on month and year picker dropdown. dont select anything. continue clicking on month and year picker dropdown to toggle between wheel picker and calendar. Year will keep going down as i toggle on and off. When i scroll down to 2024 picker dropdown shows 2023 and it propagates down to date picker when i choose a date.

### Expected behavior

should not be 2023 when i click on 2024

### Screenshots or Videos

https://github.com/user-attachments/assets/87c3401b-bfa3-4498-a663-27f719b8b966

### Operating System Version

MacOS M1, brave browser

### Browser

Other (add additional context)

**Comment by MuditxRajput** [comment] 2024-10-04 11:44
can i take this ?

**Comment by wingkwong** [comment] 2024-10-04 12:13
@MuditxRajput go ahead

**Comment by shraddha761** [comment] 2024-10-10 08:38
@wingkwong as there is no update till now can i take this

**Comment by wingkwong** [comment] 2024-10-10 11:40
@shraddha761 reassigned to u.

**Comment by shraddha761** [comment] 2024-10-11 06:54
https://github.com/user-attachments/assets/f109a649-c516-42ff-8920-1f7dcb75d72f

This bug doesn't appear in my system.

**Comment by wingkwong** [comment] 2024-10-11 07:27
couldn't reproduce in canary branch as well.

**Closed by wingkwong** 2024-10-11 07:27 UTC
