### ISSUE TITLE
Slider component not working.  Only shows label and defaultValue on screen.

### ISSUE THREAD

**Issue by fiscdupenn** [nextui-org/nextui#3417] opened 2024-07-05 19:33 UTC
### NextUI Version

"@nextui-org/slider": "^2.2.12",

### Describe the bug

Other components like button work fine.

$ npx nextui-cli@latest add slider

NextUI CLI v0.3.2

NextUI CLI: ❌ You have already added the following components: slider
 
_Screen shows:_

```
status-widget-v1
Select a value50
```

**page.tsx**

```
"use client"

import React from "react";
import { Slider } from "@nextui-org/slider"

export default function Home() {
    return (
        <div>
            <h1>status-widget-v1</h1>
            <Slider
            label="Select a value"
            step={1}
            maxValue={100}
            minValue={0}
            defaultValue={50}
            className="max-w-md"
            />
        </div>
        );
}
```

### Steps to Reproduce the Bug or Issue

npm run dev

### Expected behavior

Slider to show 0 to 100.

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by fiscdupenn** [comment] 2024-07-05 19:35
// "use client"

// import React from "react";
// import { Slider } from "@nextui-org/slider"

// export default function Home() {
//     return (
//         <div>
//             <h1>status-widget-v1</h1>
//             <Slider
//             label="Select a value"
//             step={1}
//             maxValue={100}
//             minValue={0}
//             defaultValue={50}
//             className="max-w-md"
//             />
//         </div>
//         );
// }

**Comment by ryo-manba** [comment] 2024-07-06 03:08
Sorry, the formatting of the code is not clear. Could you please provided a minimal reproduction example using Stackblitz?

**Comment by fiscdupenn** [comment] 2024-07-06 19:33
https://stackblitz.com/~/github.com/c4r-dev/status-widget-v1

code is in app/page.tsx

New to Next.js and NextUI.  Should I create a React component and add to page.tsx?   Confused that the Slider doesn't show when the Button does show.

**Comment by fiscdupenn** [comment] 2024-07-06 19:44
https://stackblitz.com/~/github.com/c4r-dev/status-widget-v1

**Comment by ryo-manba** [comment] 2024-07-11 22:58
We couldn't reproduce the issue, so we will close this issue.
Thank you, @abhinandan-verma for looking into it!

**Closed by ryo-manba** 2024-07-11 22:58 UTC
Labels: 🔎 Status: More Info Needed

**Comment by agi-v0** [comment] 2024-10-21 12:34
I had the same problem, was able to solve it by uninstalling and then reinstalling through the cli. Alternatively, add the following to your tailwind config
`
content: [
    "./node_modules/@nextui-org/theme/dist/components/(button|link|navbar|slider|tabs|popover|ripple|spinner).js",
  ],
`
