### ISSUE TITLE
[BUG] - Input component - visible border 

### ISSUE THREAD

**Issue by OndrosI** [nextui-org/nextui#1572] opened 2023-09-05 13:25 UTC
### NextUI Version

2.1.10

### Describe the bug

Hello, when i use Input controller i see this visible border. I don't know how to remove it using tailwindcss.

My tailwind config

```
import type { Config } from 'tailwindcss';
const {nextui} = require("@nextui-org/react");

const config: Config = {
  content: [
    './public/**/*.html',
    './pages/**/*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}',
    './node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [
    require('flowbite/plugin'),
    nextui(),
  ],
};
export default config;
```

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

I want input see input without default border

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/40022797/bcff7da2-27cd-477a-a865-c981b7c1aad0)

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment] 2023-09-05 13:28
Hey @OndrosI could you share a codesandbox where the issue is visible? It might be because you're also using Flowbite, maybe they add some global styles to the input

**Comment by qpenney** [comment] 2023-09-05 18:44
This is generally speaking a Chrome only matter. See: https://support.google.com/chrome/thread/48974735?hl=en

**Comment by MunasheHodza** [comment] 2023-09-16 22:38
Hey, @qpenney, having the same issue on safari, arc, chrome and edge.

**Comment by NivixX** [comment] 2023-10-11 14:40
I got the issue and find how to fix it. It was because I ways using **@tailwindcss/forms**
You can remove it from **tailwind.config.js** file

```
  plugins: [
    nextui(),,
    **require('@tailwindcss/forms'),** <-- to remove
  ],
```

**Comment by rumfiske** [comment] 2023-11-29 13:01
> I got the issue and found how to fix it. It was because I was using **@tailwindcss/forms** You can remove it from **tailwind.config.js** file
> 
> ```
>   plugins: [
>     nextui(),
>     require('@tailwindcss/forms') <-- to remove
>   ],
> ```

I have same mistake, but i dont use @tailwindcss/forms

**Comment by Loosetooth** [comment] 2024-01-22 12:22
I had the same issue.
In my case, like the OP, I had the `flowbite` plugin added to my tailwind config.
Removing that plugin fixed it for me.

**Comment by loyal812** [comment] 2024-03-27 11:15
Hello, I also had the same problem and it solved it. This is my approach.

```
            <Autocomplete
                label=""
                variant="bordered"
                radius="sm"
                inputProps={{
                    classNames: {
                        inputWrapper: "border focus-within:border-0 focus-within:ring-2 focus-within:ring-blue-500 focus-within:border-blue-500"
                    }
                }}
                name={name}
                selectedKey={value}
                placeholder={placeholder}
                onSelectionChange={(value: any) => onChange(value)}
            >
```

**Comment by wingkwong** [comment] 2024-05-16 09:30
Closing - this was due to flowbite plugin.

**Closed by wingkwong** 2024-05-16 09:30 UTC
Labels: 🐛 Type: Bug

**Comment by marian2js** [comment] 2024-05-19 15:58
> Closing - this was due to flowbite plugin.

@wingkwong The issue is also caused by `@tailwindcss/forms` which is an official plugin of tailwind, and shouldn't break NextUI imo.

**Comment by snimavat** [comment] 2024-12-25 05:52
I had same issue, removing @tailwindcss/forms from tailwind config fixed it for me
