### ISSUE TITLE
Can not find module '../utils/types' or its corresponding type declarations

### ISSUE THREAD

**Issue by PatrickNiyogitare28** [nextui-org/nextui#122] opened 2021-11-19 18:51 UTC
# Cannot find module '../utils/types' or its corresponding type declarations

Building for production is failing as `@nextui-org` is throwing the error

**Steps to reproduce**
1. Install the library using `yarn install @nextui-org/react`
2. Build for production with `yarn build`

**Expected behaviour**
The build fails with the bellow error log 
```js
yarn run v1.22.17
$ tsc && vite 
node_modules/@nextui-org/react/esm/theme/utils.d.ts:2:29 - error TS2307: Cannot find module '../utils/types' or its corresponding type declarations.

2 import { DeepPartial } from '../utils/types';
                              ~~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Screenshots**
![image](https://user-images.githubusercontent.com/54368821/142675367-97575e66-2f87-4253-a382-f014a3063dd6.png)

**Environment / Context**
- Windows 10 Pro
- Node `v16.13.0`
- Npm `8.1.3` 
- Yarn `1.22.17`
- Framework *React with vite*

**Additional info**
I like this library components, if they is any workaround that would be great for me to keep the smooth development

**Comment by carlosriveroib** [comment] 2021-11-20 13:57
This is working for me using the same versions on MacBook M1 Pro with macOS Monterey

**Comment by PatrickNiyogitare28** [comment] 2021-11-22 09:36
I deployed the app on vercel and the builds kept failing as well
Down are the logs

```js
Cloning completed: 642.855ms
Analyzing source code...
Installing build runtime...
Build runtime installed: 3.493s
Looking up build cache...
Build cache downloaded [34.64 MB]: 2257.322ms
Detected package.json
Installing dependencies...
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > jest-scss-transform@1.0.1" has incorrect peer dependency "babel-jest@^24.8.0".
[4/4] Building fresh packages...
Done in 22.43s.
Running "yarn run build"
yarn run v1.22.17
$ tsc && vite build
node_modules/@nextui-org/react/esm/theme/utils.d.ts(2,29): error TS2307: Cannot find module '../utils/types' or its corresponding type declarations.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Command "yarn run build" exited with 2
```

**Comment by OrhanTozan** [comment] 2021-11-25 21:13
@jrgarciadev I think the question label can be replaced with the bug label.

**Comment by jrgarciadev** [comment] 2021-11-25 21:22
Hey guys 🙋🏻‍♂️, I'm currently migrating the engine styles from styled-jsx to stitches, this issue should be fixed with that and a lot of features will be included 🙌🏻, I hope to release the next version by the end of the month

**Comment by PatrickNiyogitare28** [comment] 2021-11-26 06:04
Is there any community, I would like to be updated when this fixed out. I'm glad that you're working on it

**Comment by carlosriveroib** [comment] 2021-11-26 09:22
Yes, there is a Discord community. You can join here https://discord.gg/9b6yyZKmH4

**Comment by jrgarciadev** [comment] 2021-12-27 14:51
Hey  @PatrickNiyogitare28  could you please try it again with the latest version v1.0.2-alpha.1?

**Comment by PatrickNiyogitare28** [comment] 2021-12-30 22:01
Yeah sure, let me check... I will let you know

**Comment by PatrickNiyogitare28** [comment] 2021-12-30 22:55
Hey @jrgarciadev , building for vite is failing still with new error logs different to the previous one.
[here](https://github.com/PatrickNiyogitare28/nextui-vite) I created a basic vite typescript app and added [nextui](https://nextui.org/) ... We can use it regularly testing this fix, you can automatically deploy it with vercel. It also contains the current error log when build for production

**Comment by jrgarciadev** [comment] 2021-12-31 03:16
Hey @PatrickNiyogitare28 the problem is not on NextUI, it's on the tsconfig.json since is checking types on libraries which is not totally correct because NextUI has its tsconfig.json, so for fixing it you have to turn `skipLibCheck` config param off, as follows:

tsconfig.json
```json 
"skipLibCheck": false,
```

Results:
![Screenshot 2021-12-31 at 00 07 34](https://user-images.githubusercontent.com/30373425/147800817-285bba68-05d1-4f89-9974-083148909cc4.png)

**Closed by jrgarciadev** 2021-12-31 03:16 UTC
Labels: fixed: pending release

**Comment by PatrickNiyogitare28** [comment] 2021-12-31 03:22
You're right @jrgarciadev, now It builds  successfully
