### ISSUE TITLE
[BUG] - Input

### ISSUE THREAD

**Issue by kevinxmyr** [nextui-org/nextui#2358] opened 2024-02-14 20:14 UTC
### NextUI Version

^2.2.9

### Describe the bug

as the demo says in the documentation the isClearable attribute will clear the input field. i tried it on my react nextjs project it doesnt work even i put some logic onClear.

### Steps to Reproduce the Bug or Issue

no steps required it just doesnt work on a react nextjs project

### Expected behavior

i expect that the input field will clear on click with the 'x' icon when i use isClearable

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/109541263/0f003021-d4b6-4e32-b07d-f7369c025887

### Operating System Version

MacOS Sonoma 14.2.1

### Browser

Firefox

**Comment by joelrb** [comment] 2024-02-29 15:05
> ```tsx
> "use client";
> 
> import { useState } from "react";
> import { Input } from "@nextui-org/react";
> 
> export default function Home() {
>   const [value, setValue] = useState("");
> 
>   return (
>     <Input
>       value={value}
>       isClearable
>       onValueChange={setValue}
>       onClear={() => setValue("")}
>     />
>   );
> }
> ```
> 
> It works for me.

Thank you! Finally found this. I've been looking for too long.

**Comment by wingkwong** [comment] 2024-11-29 10:01
Closing - not able to reproduce in latest version.

**Closed by wingkwong** 2024-11-29 10:01 UTC
Labels: 🐛 Type: Bug
