### ISSUE TITLE
[BUG] - path is undefined when using NextUIProvider and useRouter in React component

### ISSUE THREAD

**Issue by Sw0xy** [nextui-org/nextui#2930] opened 2024-05-02 11:59 UTC
### NextUI Version

2.3.6

### Describe the bug

The bug causes a "TypeError: path is undefined" when using NextUIProvider and useRouter in a React component.

### Steps to Reproduce the Bug or Issue

   1- Import NextUIProvider and useRouter.
   2- Define a React functional component named Providers, accepting children as props.
   3 - Within Providers component, initialize useRouter hook to get the router object.
   4 - Use NextUIProvider component, passing router.push method as navigate prop.
   5 -  Encounter "TypeError: path is undefined" error during execution.

### Expected behavior

As a user, I expect that when using the NextUIProvider and useRouter within a React component, the application should function correctly without encountering any errors related to undefined paths.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/58565946/0111d374-7afa-4ba7-8b46-5bdb6abae189)
![image](https://github.com/nextui-org/nextui/assets/58565946/1cee826e-aa1e-4e37-9544-1328eb83ab6d)

### Operating System Version

Ubuntu

### Browser

Firefox

**Comment by wingkwong** [comment] 2024-05-02 12:31
Can you provide a stackblitz link for us to investigate the issue? I'm not able to reproduce. Also it seems the issue was thrown in somewhere else.

<img width="651" alt="image" src="https://github.com/nextui-org/nextui/assets/35857179/e48407ed-c8b5-4858-9209-a8fe07ffe941">

**Comment by Sw0xy** [comment] 2024-05-02 13:11
![image](https://github.com/nextui-org/nextui/assets/58565946/b484fed1-9841-4097-a49f-3eb2976ef614)
I can't do it right now but I am using empty T3 stack.

**Comment by mozisan** [comment] 2024-05-02 16:58
I think this issue is related to the update of the @react-aria/utils package.
The following diff seems to be relevant:
https://github.com/adobe/react-spectrum/commit/23182926f918b70199e01d735a09d73438c944be#diff-b47f93129ab2e1ce25df1793dca18da226bb02c43d213225bb43c47b3b43ad73R45
The interface of the arguments has changed, which appears to cause unintended behavior.

This diff is included in the latest version of the `@react-aria/utils` package (`3.24.0`).
And I was able to reproduce the issue in my environment using that version.
However, when I changed to use the previous version of the `@react-aria/utils` package (`3.23.2`), I could not reproduce the issue.

**Comment by wingkwong** [comment] 2024-05-03 06:23
I was using 3.24.0 but still didn't see the issue. please provide a stackblitz link for us to investigate.

**Comment by xylish7** [comment] 2024-05-04 11:14
I also encountered this error, but I'm still looking into how to reproduce it. It seems that the error was triggered when I added a new nextui package (the accordion one). When I removed the router from providers everything worked ok.

**Comment by xylish7** [comment] 2024-05-04 11:36
These are my current dependencies and everything works ok when passing router to NextUIProvider.

If I update for example `@nextui-org/avatar` to latetest version (2.0.27). Everything works ok.
However, if I add a `@nextui-org/accordion` or `@nextui-org/select` or upgrade `@nextui-org/button` to latest version (2.0.31), I will get the same error.

```
"dependencies": {
    "@nextui-org/avatar": "2.0.24",
    "@nextui-org/button": "2.0.27",
    "@nextui-org/card": "2.0.24",
    "@nextui-org/checkbox": "2.0.25",
    "@nextui-org/chip": "2.0.25",
    "@nextui-org/code": "2.0.24",
    "@nextui-org/divider": "2.0.25",
    "@nextui-org/input": "2.1.17",
    "@nextui-org/kbd": "2.0.25",
    "@nextui-org/link": "2.0.26",
    "@nextui-org/navbar": "2.0.27",
    "@nextui-org/popover": "2.1.15",
    "@nextui-org/snippet": "2.0.31",
    "@nextui-org/switch": "2.0.25",
    "@nextui-org/system": "2.0.15",
    "@nextui-org/tabs": "2.0.26",
    "@nextui-org/theme": "2.1.18",
    "@nextui-org/tooltip": "2.0.30",
    "@react-aria/ssr": "3.9.2",
    "@react-aria/visually-hidden": "3.8.10",
    "@types/node": "20.12.7",
    "@types/react": "18.2.76",
    "@types/react-dom": "18.2.25",
    "autoprefixer": "10.4.19",
    "bright": "0.8.5",
    "clsx": "2.1.0",
    "dayjs": "1.11.10",
    "framer-motion": "11.0.28",
    "gray-matter": "4.0.3",
    "next": "14.2.0",
    "next-mdx-remote": "4.4.1",
    "next-themes": "0.2.1",
    "phosphor-react-sc": "1.0.0",
    "postcss": "8.4.38",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "rehype-autolink-headings": "7.1.0",
    "rehype-slug": "6.0.0",
    "remark-gfm": "3.0.1",
    "sass": "1.74.1",
    "tailwind-variants": "0.2.1",
    "tailwindcss": "3.4.3",
    "typescript": "5.4.5"
  },
  "devDependencies": {
    "@fec/remark-a11y-emoji": "4.0.2",
    "@typescript-eslint/eslint-plugin": "7.6.0",
    "@typescript-eslint/parser": "7.6.0",
    "eslint": "8.57.0",
    "eslint-config-next": "14.2.0",
    "favicons": "7.2.0"
  }
  ```

**Comment by xylish7** [comment] 2024-05-04 11:49
The error can be reproduced here: https://stackblitz.com/edit/stackblitz-starters-dkwe9f?file=README.md

**Comment by wingkwong** [comment] 2024-05-06 15:21
The [fix](https://github.com/nextui-org/nextui/commit/73d96959945820981b8a4c0e3175c13e3d1c1499) will be available in the next release. At the same time, you can use our canary version as a workaround if necessary.

```json
"@nextui-org/system": "0.0.0-canary-20240504162810"
```

update `NextUIProvider` to use `@nextui-org/system`

```tsx
import { NextUIProvider } from "@nextui-org/system";
```

**Comment by hkmute** [comment] 2024-06-01 04:55
Is the fix released in 2.4? Path is still undefined in NextUIProvider navigate argument after upgrading

**Comment by wingkwong** [comment] 2024-06-01 05:00
@hkmute please remove your node_modules, and reinstall 2.4.1. If it still fails, please share a stackblitz project.

**Comment by hkmute** [comment] 2024-06-06 15:04
> @hkmute please remove your node_modules, and reinstall 2.4.1. If it still fails, please share a stackblitz project.

@wingkwong https://stackblitz.com/~/github.com/hkmute/remix-nextui?file=app/root.tsx
![image](https://github.com/nextui-org/nextui/assets/54314549/8636c7c0-4370-4456-8d6b-f83aa4495b97)

**Comment by wingkwong** [comment] 2024-06-08 11:07
@hkmute after digging a bit, i could see this issue only when I use npm. it works fine with pnpm.

**Closed** 2024-06-15 00:45 UTC
Labels: 🐛 Type: Bug, 📦 Scope : Components
