### ISSUE TITLE
[BUG] - Accordion not  collapsing if clicked too fast

### ISSUE THREAD

**Issue by kodobrody** [nextui-org/nextui#2727] opened 2024-04-16 00:12 UTC
### NextUI Version

2.2.10

### Describe the bug

Hey, I have pretty strange problem. I tried to use `Accordion` and `AccordionItem` components, however clicking them too fast makes accordion incollapsible. height tries going from `auto` to current height in px, to 0, but after that it goes back to auto causing a flicker. I thought that this was the problem with my configuration, but I set up a new next.js project, tried it and reproduced.

### Steps to Reproduce the Bug or Issue

1. Create new next.js project (I usep app directory with src)
2. setup tailwind and next ui according to guides:
a) npm install -D tailwindcss postcss autoprefixer
b) npx tailwindcss init -p
c) add content to tailwind.config.js (just the one for src directory)
d) add @tailwind base, components, utilities to `globals.css`
e) add @nextui-org/react framer-motion
f) add to tailwind config: `const {nextui} = require("@nextui-org/react");` and `"./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}"` to config, and those separate keys `darkMode: "class"`, `plugins: [nextui()]`
g) Add `Providers` client component and then wrap children with it inside `Layout.tsx`
h) create client component:
```
import { Accordion, AccordionItem } from "@nextui-org/accordion";

export const Acc = () => (
  <Accordion>
    <AccordionItem key="1">
      span
    </AccordionItem>
  </Accordion>
)
```

i) run the app, click quickly accordion at least three times
j) It will try to close, but will reopen causing flicker

### Expected behavior

Accordion should collapse

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/117864696/b5a39846-8b2d-44b2-9128-01d967980a88

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment] 2024-04-16 03:57
@kodobrody I'm not able to reproduce the issue locally. (Chrome but I'm using mac tho)

- can you share the version of `framer-motion`?
- can you try this canary version `@nextui-org/accordion@0.0.0-dev-v2-20240416003301`?

**Comment by kodobrody** [comment] 2024-04-16 08:19
@wingkwong I was using `framer-motion` version `11.0.28`, which was the latest as of time you checked (`11.1` was released like 30 minutes ago), however the canary version of accordion fixes the issue. Could you possibly tell what was wrong?

**Comment by wingkwong** [comment] 2024-04-16 08:25
@kodobrody I can't tell which commit fixing the issue but there was some changes done in accordion related to framer-motion. You may wait for the next release which should be coming soon.

**Comment by wingkwong** [comment] 2024-04-18 10:44
Closing - as we already released.

**Closed by wingkwong** 2024-04-18 10:44 UTC
Labels: 🐛 Type: Bug
