### ISSUE TITLE
[BUG] - Table.Pagination components doesn't update the number of pages displayed when the table data changes

### ISSUE THREAD

**Issue by TarsiSurdi** [nextui-org/nextui#543] opened 2022-06-13 01:30 UTC
### Describe the bug

I'm updating the data within a table through a dropdown selector for different sets of data.

Once the data being displayed updates, the number of pages shown by the pagination components doesn't reflect the change properly.

For example, if a dataset has less items than the previous, more pages than necessary are available for the user to choose from. Also, if the initial dataset had less items than the one selected by the user, additional data wouldn't span to extra pages and that date couldn't be accessed / displayed. I had to solve that issue by defaulting the data displayed to the dataset with more items in it, this way no data gets hidden but additional pages are shown on all of the other datasets.

### Your Example Website or App

https://buscavet.vercel.app/

### Steps to Reproduce the Bug or Issue

1. Go to the website.
2. Click any of the following buttons: "Medicações", "Vacinas", "Suplementos" or "Desinfetantes".
3. Try changing the dataset displayed on the table below it through the dropdown menu.
4. Observe pages not updating accordingly to the ammount of rows being displayed.

### Expected behavior

The number of pages updates according to the number of rows contained in the table.
I'm not sure if this is something related to my implementation of that component, but I certainly expected it to work the way I did it...

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/19439765/173263925-555da9a1-7815-4c81-87b0-d8698c3aa867.png)
![image](https://user-images.githubusercontent.com/19439765/173263952-2b97a499-b5eb-4fda-9089-38a28c6ce3a8.png)
![image](https://user-images.githubusercontent.com/19439765/173263972-24026f0d-1a4b-467d-bb3b-0c8e2e303dfd.png)

### Operating System Version

Linux (Fedora 36)

### Browser

Firefox

**Comment by TarsiSurdi** [comment] 2022-06-13 01:33
Also, if you want to take a look at my code, the repo for the website in question is available here: [Buscavet Repository](https://github.com/TarsiSurdi/buscavet)

**Comment by TarsiSurdi** [comment] 2022-06-13 02:09
I stumbled uppon issue #324 and it shed some light into some non documented props of the Pagination component that I was able to implement on my app. Now the size of the pagination updates accordingly to the dataset. 

But there's a new issue: if you select a page like "4" and change the dataset to a smaller one, the page goes back to the first one (as I implemented on my code) but the contents of the table on that page do not show up...
This time I really think this is an issue with the lib and not with my code.

**Comment by imchell** [comment] 2022-06-13 05:02
I can reproduce the bug when `<Table.Pagination />`'s `total` attribute is controlled manually. Looking into the issue. Thanks.

**Comment by jrgarciadev** [comment] 2022-07-21 12:35
Hey @TarsiSurdi thanks for reporting this, since you were able to solve the original issue, I'm going to close this issue and please follow up on the mentioned issue about "the page goes back to the first one" here https://github.com/nextui-org/nextui/issues/619

**Closed by jrgarciadev** 2022-07-21 12:35 UTC
Labels: bug
