### ISSUE TITLE
[BUG] - isClearable is not working

### ISSUE THREAD

**Issue by Lqast** [nextui-org/nextui#2027] opened 2023-11-23 18:08 UTC
### NextUI Version

2.2.9

### Describe the bug

I don't know why this happens but when I try to clear the input it doesn't, the value stays the same as before.

Im using NextJS 14.0.3

### Steps to Reproduce the Bug or Issue

I don't have steps, I just copied it from the documentation and it didn't work, and I tried many things to fix it but it didn't work

### Expected behavior

Well, as the documentation says, I hope it clears itself when I hit 'x'

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/103293995/016abf7d-42e8-443e-8386-7cb0bb35f3b2
![image_2023-11-23_095718585](https://github.com/nextui-org/nextui/assets/103293995/69027e75-9a3d-462f-b767-34234b796642)
![image](https://github.com/nextui-org/nextui/assets/103293995/8c73f827-d487-4eb9-bf99-bde69cbb4749)

### Operating System Version

Windows 11

### Browser

Chrome

**Comment by black197** [comment] 2023-11-24 10:06
seems like duplicate of #1984

**Comment by jrgarciadev** [comment] 2023-11-24 11:18
Duplicated #1984

**Closed by jrgarciadev** 2023-11-24 11:18 UTC
Labels: bug
