### ISSUE TITLE
[BUG] - Avatar

### ISSUE THREAD

**Issue by Heisen-erg** [nextui-org/nextui#3950] opened 2024-10-27 08:14 UTC
### NextUI Version

2.4.0

### Describe the bug

isbordered property and color property not working properly

### Steps to Reproduce the Bug or Issue

use isbordered property of avatar component in Next.js

### Expected behavior

border should be visible when giving true to isbordered property

### Operating System Version

windows

### Browser

Chrome

**Comment by ShrinidhiUpadhyaya** [comment] 2024-10-27 10:52
Couldn't reproduce, can you please provide a sandbox.

**Comment by wingkwong** [comment] 2024-10-27 11:15
please try latest version.

**Comment by elartix** [comment] 2024-11-05 14:10
`Avatar` component will throw error `does not recognize the 'disableAnimation'` when applied next.js Image component for `ImgComponent` or `fallback`. 

```
Warning: React does not recognize the 'disableAnimation' prop on a DOM element. 
If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase 'disableanimation' instead. 
If you accidentally passed it from a parent component, remove it from the DOM element.
    at img
    at eval (webpack-internal:///(ssr)/./node_modules/next/dist/client/image-component.js:133:11)
    at eval (webpack-internal:///(ssr)/./node_modules/next/dist/client/image-component.js:242:47)
    at div
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/avatar/dist/chunk-QXREVWCS.mjs:17:369)
    at button
    at ot (webpack-internal:///(ssr)/./node_modules/@headlessui/react/dist/components/menu/menu.js:283:57)
```

### Steps to Reproduce the Bug or Issue

```typescript
import Image from 'next/image';

import userAvatarImg from '@/assets/images/user-default.svg';

export const BaseUserProfileAvatar = memo(function BaseUserProfileAvatar ({ user }: BaseUserProfileAvatarProps) {
  const userFullName = `${user?.firstName} ${user?.lastName}`;
  const userAvatarUrl = _.get(user, 'profile.avatarUrl', '');

  return <Avatar
    as="div"
    radius="full"
    showFallback
    alt={userFullName}
    src={userAvatarUrl}
    name={userFullName}
    ImgComponent={Image}
    imgProps={{
      width: 32,
      height: 32,
    }}
    className="h-8 w-8"
    classNames={{
      base: 'bg-[#f4f4f4]',
      fallback: 'w-full h-full',
    }}
    fallback={<Image
      width={32}
     height={32}
      alt={userFullName}
      src={userAvatarImg}
      className="h-8 w-8"
    />}
  />;
});
```

**Comment by wingkwong** [comment] 2024-11-05 15:10
@elartix i rmb this has been fixed. please wait for the next release.

**Comment by elartix** [comment] 2024-11-05 15:27
> @elartix i rmb this has been fixed. please wait for the next release.

Thsnk you

**Comment by wingkwong** [comment] 2024-12-04 14:59
Closing - no reproducible environment provided by OP

**Closed by wingkwong** 2024-12-04 14:59 UTC
Labels: 📃 Status: Reproducible Environment Needed
