### ISSUE TITLE
[BUG] - Cannot Change Value after select item in Autocomplete

### ISSUE THREAD

**Issue by anungbisa4** [nextui-org/nextui#3213] opened 2024-06-07 10:30 UTC
### NextUI Version

2.4.0

### Describe the bug

https://codesandbox.io/p/devbox/staging-firefly-zrszzv?file=%2FApp.jsx

every default items is like this
 const data = [
  { value: "1", label: "1" },
  { value: "2", label: "2" },
];
  or numbers always cannot be selected
  
  but if 
   const data = [
  { value: "1", label: "1 test" },
  { value: "2", label: "2 test" },
]; that is correct and appropriate

That's very weird and should work for all the cases above

### Your Example Website or App

https://codesandbox.io/p/devbox/staging-firefly-zrszzv?file=%2FApp.jsx

### Steps to Reproduce the Bug or Issue

goto autocomplete component 
select item
nothing happened

### Expected behavior

should work for all the cases above and should be selected

### Operating System Version

mac os

### Browser

Chrome

**Comment by srivatsa17** [comment] 2024-06-07 11:31
This is duplicate of #2955

**Closed** 2024-06-08 07:05 UTC
