### ISSUE TITLE
[BUG] - Select opens and closes instantly when clicking on the label

### ISSUE THREAD

**Issue by danielantelo** [nextui-org/nextui#3558] opened 2024-07-25 16:00 UTC
### NextUI Version

~~2.4.6~~ 2.4.8

### Describe the bug

Just upgraded to the latest version and now my Selects are not behaving properly. When I click on the label of a Select it used to Open and allow user to select an option. Now it opens and instantly closes. I see it is also happening on your Docs website.

### Your Example Website or App

https://nextui.org/docs/components/select

### Steps to Reproduce the Bug or Issue

1. Go to https://nextui.org/docs/components/select
2. Click on the label of any of the Selects
3. Notice how it opens and closes instantly

### Expected behavior

When you click on the Label it should remain open.

### Screenshots or Videos

https://github.com/user-attachments/assets/c4dac053-244c-4ea4-bbf7-4c8dc29cfa2e

### Operating System Version

MacOS

### Browser

Chrome

**Comment by wingkwong** [comment] 2024-07-25 16:46
can ref to `ariaShouldCloseOnInteractOutside` logic. the trigger is only on input so label is considered outside.

**Comment by sohan01fw** [comment] 2024-07-26 08:16
@wingkwong can u assign this to me? i solved it. Need to raise pr

**Comment by sohan01fw** [comment] 2024-07-27 03:49
@wingkwong  i  have one question do i need to run test and build to the specific component that i made changes or whole? cause during build of whole project got error but not while doing on specific component that i made changes on!

**Comment by wingkwong** [comment] 2024-07-27 06:44
@sohan01fw of course all test cases have to be passed. If some that you haven't changed fail, then some underlying logic may be changed. You may double check.

**Comment by sohan01fw** [comment] 2024-07-28 04:04
i don't like this i don't know why the error still presist even tho i freshly fork and clone repo again and try to build the project without made any changes throw some wired error like this 
![Screenshot (48)](https://github.com/user-attachments/assets/b148e3a0-dea6-43ab-aab2-6da737bd3ad2)

**Comment by wingkwong** [comment] 2024-07-28 05:52
@sohan01fw if so, then probably it's related to your local environment rather than your PR. Can yo make a PR so that it could run in github actions to see if the errors are still there?

**Comment by Gaic4o** [comment] 2024-07-29 03:26
During QA testing on the service, this problem was discovered. I hope it gets resolved quickly.

**Comment by kanstantsinkamazennikau** [comment] 2024-07-29 17:11
Perhaps there is some sort of fix that can be used now before the PR merged?

**Comment by abhinav700** [comment] 2024-09-24 05:22
@wingkwong I notie that you have rolled back the associated PR.
Is this issue still open?

**Comment by wingkwong** [comment] 2024-09-24 05:23
@abhinav700 yep. thanks for the catch.

**Comment by abhinav700** [comment] 2024-09-24 05:36
@wingkwong Ok. I will begin investigating the issue. Will update if I find something. Right now I am looking into `ariaShouldCloseOnInteractOutside` to get better context and implement the solution suggested by you.

**Comment by abhinav700** [comment] 2024-09-24 06:32
@wingkwong  It seems like I cannot reproduce this issue on my local machine, even though I have synced my branch and pulled the changes.

Maybe it is fixed in some other PR which was not referencing this issue using a `#`.

https://github.com/user-attachments/assets/e1c10f17-b0c3-4474-a9b3-635f6e1ba963

**Comment by wingkwong** [comment] 2024-09-24 06:36
just checked. the only i rolled back is 3658, not 3568, which just mentioned by coderabbit only.

**Closed by wingkwong** 2024-09-24 06:36 UTC
Labels: 🐛 Type: Bug, 📦 Scope : Components

**Comment by abhinav700** [comment] 2024-09-24 06:40
@wingkwong ok.
