### ISSUE TITLE
[BUG] - When clicking a <Link /> component with a HREF attribute I get an error in the console.

### ISSUE THREAD

**Issue by jcsabin** [nextui-org/nextui#3046] opened 2024-05-22 09:26 UTC
### NextUI Version

2.3.1

### Describe the bug

I recently updated all my packages in my project to the latest version and it seems to have broken the routing setup with nextJS and NextUI.

Everywhere I have a NextUI component that contains a HREF that used to work previously now displays the following error

`Cannot read properties of undefined (reading 'startsWith')`

My deps are as follows

` "dependencies": {
    "@heroicons/react": "^2.0.18",
    "@hookform/error-message": "^2.0.1",
    "@internationalized/date": "^3.5.2",
    "@nextui-org/button": "^2.0.28",
    "@nextui-org/card": "^2.0.28",
    "@nextui-org/checkbox": "^2.0.29",
    "@nextui-org/date-picker": "^2.0.6",
    "@nextui-org/dropdown": "^2.1.22",
    "@nextui-org/input": "^2.1.18",
    "@nextui-org/progress": "^2.0.28",
    "@nextui-org/radio": "^2.0.28",
    "@nextui-org/react": "^2.3.1",
    "@nextui-org/select": "^2.1.22",
    "@nextui-org/system": "^2.1.0",
    "@nextui-org/tabs": "^2.0.27",
    "@nextui-org/theme": "^2.2.3",
    "@reduxjs/toolkit": "^1.9.5",
    "@types/node": "20.2.6",
    "@types/react": "18.2.10",
    "@types/react-dom": "18.2.4",
    "autoprefixer": "10.4.14",
    "classnames": "^2.3.2",
    "encoding": "^0.1.13",
    "eslint": "8.42.0",
    "eslint-config-next": "^13.5.3",
    "firebase": "^10.12.1",
    "framer-motion": "^11.1.1",
    "moment": "^2.29.4",
    "next": "^14.0.4",
    "nextui-cli": "^0.2.0",
    "postcss": "8.4.24",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.45.2",
    "react-redux": "^8.1.2",
    "recharts": "^2.8.0",
    "redux": "^4.2.1",
    "tailwindcss": "^3.3.2",
    "typescript": "5.1.3"
  },`

Screenshots of my routing setup
_app.tsx file
<img width="484" alt="Screenshot 2024-05-22 at 10 23 53" src="https://github.com/nextui-org/nextui/assets/81153042/b8af62f3-2b82-41de-a341-10031d18408e">

My Providers file
<img width="738" alt="Screenshot 2024-05-22 at 10 24 27" src="https://github.com/nextui-org/nextui/assets/81153042/3ce4a410-07e9-4ea0-bf8e-3546c6c52bbc">

### Steps to Reproduce the Bug or Issue

1) set up a <Link/> component with a HREF 

e.g

<Link href="/test">Text Here</Link>

2) Click on the the link in the FE app and then it doesn't redirect the user to that page it throws the error as stated above.

### Expected behavior

It should redirect the user to the page clicked on

### Screenshots or Videos

<img width="830" alt="Screenshot 2024-05-22 at 10 25 46" src="https://github.com/nextui-org/nextui/assets/81153042/811ee14f-5418-45eb-afda-c8f6d60e86d9">

### Operating System Version

MacOS

### Browser

Chrome

**Comment by wingkwong** [comment] 2024-05-22 09:39
duplicate of https://github.com/nextui-org/nextui/issues/2934. see the last comment there.

**Closed by wingkwong** 2024-05-22 09:39 UTC

**Comment by jcsabin** [comment] 2024-05-22 12:39
> duplicate of #2934. see the last comment there.

<img width="693" alt="Screenshot 2024-05-22 at 13 38 36" src="https://github.com/nextui-org/nextui/assets/81153042/3af2cd90-adee-47e5-8af4-2078f18e2082">

Appreciate your taking the time to link that but I swapped all that around in the last comment on the post you linked and unless I'm doing something stupid, it's throwing errors.

**Comment by wingkwong** [comment] 2024-05-22 13:10
@jcsabin please DM me in [discord](https://discordapp.com/users/495466997304262658)
