### ISSUE TITLE
[BUG] - Links is not working with react-router-dom

### ISSUE THREAD

**Issue by tareq96** [nextui-org/nextui#2963] opened 2024-05-08 05:59 UTC
### NextUI Version

2.3.6

### Describe the bug

I'm using Vite with React ts template and react-router-dom for routing.
When I switched to the latest version of NextUI, the links stopped working.

<img width="719" alt="image" src="https://github.com/nextui-org/nextui/assets/19652643/633b4c1e-b58f-4371-870f-2fe05d172772">

<img width="777" alt="image" src="https://github.com/nextui-org/nextui/assets/19652643/c6bfe3bf-23de-4fb4-b22a-931d66904904">

<img width="823" alt="image" src="https://github.com/nextui-org/nextui/assets/19652643/b9638d0a-200b-442c-b142-52d730e3c11e">

### Steps to Reproduce the Bug or Issue

Just adding any link

### Expected behavior

The expected behavior is to make the links navigate to the right URL without reloading the page.

### Operating System Version

macOS

### Browser

Chrome

**Comment by wingkwong** [comment] 2024-05-08 07:15
I also found the same issue days ago. Somehow it works when I link to local nextui Link package. Probably it is due to some upgraded internal react aria versions messing up. May wait for the next release to see if this is resolved or not.

**Comment by wingkwong** [comment] 2024-05-08 13:39
@tareq96 I don't have the date yet since we still got several PR reviews going on. At the same time, can you use the downgraded version instead? I just tested the following version could resolve the problem.

```
"@nextui-org/link": "2.0.22"
```

**Comment by tareq96** [comment] 2024-05-08 17:04
will do, thanks @wingkwong

**Comment by maxprilutskiy** [comment] 2024-05-20 18:29
I can confirm that this issue completely breaks a Remix js web app. We upgraded to the latest nextui, and our whole platform stopped functioning because of broken links.

Please prioritize, if possible! 🙏

**Comment by johnmangan** [comment] 2024-05-21 00:20
We've also hit the issue with our Nextjs app.

After spending some time inside the nextjs code, I found the link/path was being passed in as undefined.

Looking into the NextUI docs ([here](https://nextui.org/docs/guide/routing#nextjs)), I decided to validate at the `NextUIProvider` level. I changed `<NextUIProvider navigate={router.push}>` into
```tsx
<NextUIProvider
  navigate={(...args) => {
    console.log("NextUIProvider.navigate", ...args);
    return router.push(...args);
  }}
>
```

Output from clicking on a link, e.g., `<Link href="/fubar">` is:
```
NextUIProvider.navigate undefined undefined

```

**Comment by maxprilutskiy** [comment] 2024-05-21 14:38
@johnmangan yep, exactly this!

Here's a stackblitz repro: https://stackblitz.com/edit/remix-run-remix-nrotvl?file=app%2Froot.tsx

cc @wingkwong

**Comment by maxprilutskiy** [comment] 2024-05-21 21:22
gotcha, @wingkwong , thank you very much!

any rough estimate when the new version will be rolled out? could help with planning on our side.

**Comment by maxprilutskiy** [comment] 2024-05-21 21:40
@wingkwong i've just added these lines to package.json

```
  "resolutions": {
    "@nextui-org/link": "0.0.0-canary-20240520130845",
    "@nextui-org/system": "0.0.0-canary-20240520130845"
  }
```

and the error is still there, I'm afraid! 

https://stackblitz.com/edit/remix-run-remix-nrotvl?file=package.json

**Comment by wingkwong** [comment] 2024-05-22 02:15
@maxprilutskiy Sorry for not making it clean. You need to update the import lines as well in order to use the canary packages. 

menu.tsx

```diff
- import { Link } from '@nextui-org/react';
+ import { Link } from '@nextui-org/link';
```

root.tsx
```diff
- import { NextUIProvider } from '@nextui-org/react';
+ import { NextUIProvider } from '@nextui-org/system';
```

or check my forked stackblitz: https://stackblitz.com/edit/remix-run-remix-quqyzd

> any rough estimate when the new version will be rolled out? could help with planning on our side.

we rescheduled to 24th May.

**Comment by maxprilutskiy** [comment] 2024-05-22 06:47
@wingkwong thanks for sharing the example!

Links now indeed trigger navigation, but I'm afraid they now cause the page to reload entirely.

Can you confirm you see the same?

**Comment by niclas-j** [comment] 2024-05-22 17:06
Can also confirm that after downgrading to the Link version 2.0.22 the passed path is no longer undefined but a full page reload is happening. Using newly created next 14 project.

**Comment by wingkwong** [comment] 2024-05-23 07:56
@niclas-j I couldn't reproduce on next 14 project. Can you share the stackblitz project? also have you tried the above canary versions?

**Comment by MerryOscar** [comment] 2024-05-23 15:22
can confirm downgrading to `"@nextui-org/link": "2.0.22"` solved the issue for me.

@wingkwong not sure if the issue has anything to do with these changes but thought I'd share in case helpful:

- https://github.com/adobe/react-spectrum/pull/5864
- https://github.com/adobe/react-spectrum/issues/6397
- https://github.com/adobe/react-spectrum/pull/6346

**Comment by wingkwong** [comment] 2024-05-23 15:39
@MerryOscar Please note that downgrading is just a workaround until the next release (target: 24th May). `useHref` was introduced in 1st May '24 release of React Aria which our current version (or the next version) of NextUI hasn't integrated with. I've a draft PR for that already and we plan it to integrate with updated react aria version on 2.5.0 tentatively.

**Comment by niclas-j** [comment] 2024-05-23 16:18
> @maxprilutskiy confirmed it would cause full page reload even with canary versions. will investigate it.
> 
> @niclas-j I couldn't reproduce on next 14 project. Can you share the stackblitz project? also have you tried the above canary versions?

Stackblitz wont load for me right now, here I uploaded it as a repo:
https://github.com/niclas-j/next-ui-navigation-bug

Note that I also tried `"@nextui-org/link": "2.0.22",` + `@nextui-org/system": "2.1.0`

**Comment by deyvtech** [comment] 2024-05-25 06:09
> @tareq96 I don't have the date yet since we still got several PR reviews going on. At the same time, can you use the downgraded version instead? I just tested the following version could resolve the problem.
> 
> ```
> "@nextui-org/link": "2.0.22"
> ```

still not working

**Comment by wingkwong** [comment] 2024-05-25 07:10
@deyvtech can you provide your repo or stackblitz project?

**Comment by deyvtech** [comment] 2024-05-25 07:12
https://github.com/deyvtech/FashionNexus

**Comment by wingkwong** [comment] 2024-05-27 16:22
closing - please use the latest version (v2.4.0)

**Closed by wingkwong** 2024-05-27 16:22 UTC
Labels: 🐛 Type: Bug, 📦 Scope : Components

**Comment by maxprilutskiy** [comment] 2024-06-06 19:14
Amazing, thank you very much @wingkwong!

Everything now works! 🎉

**Comment by march1993** [comment] 2024-06-07 17:36
> We've also hit the issue with our Nextjs app. I assume these are related, although it's possible that it's just a coincidence.
> 
> After spending some time inside the nextjs code, I found the link/path was being passed in as undefined.
> 
> Looking into the NextUI docs ([here](https://nextui.org/docs/guide/routing#nextjs)), I decided to validate at the `NextUIProvider` level. I changed `<NextUIProvider navigate={router.push}>` into
> 
> ```tsx
> <NextUIProvider
>   navigate={(...args) => {
>     console.log("NextUIProvider.navigate", ...args);
>     return router.push(...args);
>   }}
> >
> ```
> 
> Output from clicking on a link, e.g., `<Link href="/fubar">` is:
> 
> ```
> NextUIProvider.navigate undefined undefined
> ```

I'm afraid ListboxItem href also breaks 😥
