### ISSUE TITLE
[BUG] - Warning: React does not recognize the `originalProps` prop on a DOM element.

### ISSUE THREAD

**Issue by joelrb** [nextui-org/nextui#2528] opened 2024-03-15 05:56 UTC
### NextUI Version

2.2.10

### Describe the bug

On running the app locally this warning is displayed:

Warning: React does not recognize the `originalProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `originalprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at span
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/avatar/dist/chunk-XBMXQVV7.mjs:17:369)
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/popover/dist/chunk-K4VREUER.mjs:23:115)
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/dropdown/dist/chunk-63RZRIL7.mjs:15:108)
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/popover/dist/chunk-I7AEEVL3.mjs:21:13)
    at Dropdown (webpack-internal:///(ssr)/./node_modules/@nextui-org/dropdown/dist/chunk-FHP3QEBP.mjs:17:13)
    at div
    at div
    at UserButton (webpack-internal:///(ssr)/./components/auth/user-button.tsx:22:87)
    at li
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/navbar/dist/chunk-MG5LCNUN.mjs:19:13)
    at ul
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/navbar/dist/chunk-PSG7VTZC.mjs:18:13)
    at header
    at nav
    at eval (webpack-internal:///(ssr)/./node_modules/@nextui-org/navbar/dist/chunk-CMNN5TJ7.mjs:25:13)
    at Navbar (webpack-internal:///(ssr)/./components/header/navbar.tsx:39:87)
    at Lazy
    at div
    at f (webpack-internal:///(ssr)/./node_modules/next-themes/dist/index.module.js:8:597)
    at $ (webpack-internal:///(ssr)/./node_modules/next-themes/dist/index.module.js:8:348)
    at $ea8dcbcb9ea1b556$export$323e4fc2fa4753fb (webpack-internal:///(ssr)/./node_modules/@react-aria/utils/dist/import.mjs:508:21)
    at div
    at $f57aed4a881a3485$var$OverlayContainerDOM (webpack-internal:///(ssr)/./node_modules/@react-aria/overlays/dist/import.mjs:1069:54)
    at $f57aed4a881a3485$export$178405afcd8c5eb (webpack-internal:///(ssr)/./node_modules/@react-aria/overlays/dist/import.mjs:1036:21)
    at $f57aed4a881a3485$export$bf688221f59024e5
    at $18f2051aff69b9bf$export$a54013f0d02a8f82 (webpack-internal:///(ssr)/./node_modules/@react-aria/i18n/dist/real-module.mjs:170:19)
    at NextUIProvider (webpack-internal:///(ssr)/./node_modules/@nextui-org/system/dist/chunk-HRMF5D3P.mjs:15:3)
    at NextProvider (webpack-internal:///(ssr)/./providers/nextuiprovider.tsx:17:25)
    at Lazy
    at body
    at html
    at SessionProvider (webpack-internal:///(ssr)/./node_modules/next-auth/react.js:232:13)
    at Lazy
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:72:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/redirect-boundary.js:80:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:84:9)
    at HotReload (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:308:11)
    at Router (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:177:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:113:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/error-boundary.js:159:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/next/dist/client/components/app-router.js:517:13)
    at Lazy
    at Lazy
    at rw (D:\Projects\Seira\Web\seiraclient\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:15737)
    at rw (D:\Projects\Seira\Web\seiraclient\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:15737)
    at ServerInsertedHTMLProvider (D:\Projects\Seira\Web\seiraclient\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:21384)
 ✓ Compiled in 1411ms (1350 modules)

### Steps to Reproduce the Bug or Issue

Run the app locally on pc.

### Expected behavior

No warnings.

### Operating System Version

Windows

### Browser

Edge

**Comment by wingkwong** [comment] 2024-03-15 07:32
duplicate of #2474

**Closed** 2024-03-15 23:55 UTC
Labels: bug
