### ISSUE TITLE
[BUG] - Component Select - required attribute

### ISSUE THREAD

**Issue by azecm** [nextui-org/nextui#1795] opened 2023-10-21 13:07 UTC
### NextUI Version

2.1.13

### Describe the bug

https://nextui.org/docs/components/select

My IDE warns about empty required attributes - 18 pieces
- Element Select doesn't have required attribute disableAnimation
- Element Select doesn't have required attribute fullWidth
- Element Select doesn't have required attribute isLabelPlaceholder
- ....

It's not a big problem, but I want...

### Steps to Reproduce the Bug or Issue

1) open webStorm IDE
2) create file .tsx
3) write
`function Test(){
  return <Select />;
}`

### Expected behavior

The attribute settings are correctly specified for the component.

### Screenshots or Videos

![Снимок экрана 2023-10-21 в 15 59 17](https://github.com/nextui-org/nextui/assets/8199031/ede7bb1f-f86a-48fa-ab7a-eb6ed11b663b)

### Operating System Version

macos

### Browser

Chrome

**Comment by mister-mist** [comment] 2023-11-09 17:32
I was not able to reproduce this anymore when I upgraded to NextUi 2.2.8. I think you can close this issue.

**Comment by wingkwong** [comment] 2024-04-05 06:44
Not reproducible + inactivity.

**Closed by wingkwong** 2024-04-05 06:44 UTC
Labels: bug
