### ISSUE TITLE
[BUG] - Hydration error on next-themes provider

### ISSUE THREAD

**Issue by gltched-usr** [nextui-org/nextui#4395] opened 2024-12-18 11:59 UTC
### NextUI Version

2.4.2

### Describe the bug

When I follow the guide on how to setup dark mode theme switcher I get an `Hydration failed because the server rendered HTML didn't match the client. As a result this tree will be regenerated on the client. This can happen if a SSR-ed Client Component used` error.

Specifically `className="dark"` and `style={{color-scheme:"dark"}`seem to cause the error ("Stacktrace" from the error):
```
 ...
  <Router actionQueue={{state:{...}, ...}} assetPrefix="">
    <HistoryUpdater>
      <RuntimeStyles>
        <HotReload assetPrefix="">
          <ReactDevOverlay state={{nextId:1, ...}} dispatcher={{...}}>
            <DevRootHTTPAccessFallbackBoundary>
              <HTTPAccessFallbackBoundary notFound={<NotAllowedRootHTTPFallbackError>}>
                <HTTPAccessFallbackErrorBoundary pathname="/signin" notFound={<NotAllowedRootHTTPFallbackError>} ...>
                  <RedirectBoundary>
                    <RedirectErrorBoundary router={{...}}>
                      <Head>
                        <link>
                          <RootLayout>
                            <html
                              lang="en"
                                >
                                  ...
                                    ...
-                                className="dark"
-                                style={{color-scheme:"dark"}}
```

### Steps to Reproduce the Bug or Issue

Follow the docs:
1. Add next-themes
2. Create the providers.js file with the content from the docs
3. Wrap the app (`layout.js` in the <Providers> (imported from `providers.js`)
4. Get the hydration error

### Expected behavior

No Hydration Error

### Operating System Version

macOS

### Browser

Safari

**Comment by wingkwong** [comment] 2024-12-18 12:08
1. have you tried the latest version?
2. If it still fails, please provide a minimal reproducible environment.

**Comment by wingkwong** [comment] 2024-12-18 12:42
can you also provide your package.json?

**Comment by wingkwong** [comment] 2024-12-18 14:16
I'm going close this since it's due to `next-themes`. There's another alternative by setting `suppressHydrationWarning` to `true`.

**Closed by wingkwong** 2024-12-18 14:16 UTC
