### ISSUE TITLE
[Feature Request] Select Searchable

### ISSUE THREAD

**Issue by WilliamBRDrive** [nextui-org/nextui#1821] opened 2023-10-27 16:54 UTC
### Is your feature request related to a problem? Please describe.

It's a problem when I have a select with several options to choose from

### Describe the solution you'd like

When, for example, using a select box that lists 100 services, and the user has to select one of them

### Describe alternatives you've considered

Having the ability in the Select menu to search for a specific item you want, instead of scrolling to find it

### Screenshots or Videos

https://mantine.dev/core/select/#searchable

**Comment by toxsick** [comment] 2023-11-01 01:58
Duplicate of #1586

**Comment by jrgarciadev** [comment] 2023-11-06 13:58
Use the https://nextui.org/docs/components/autocomplete component.

**Closed by jrgarciadev** 2023-11-06 13:58 UTC
Labels: feature request
