### ISSUE TITLE
[BUG] - Pagination Component Displays Incorrect Page Number in RTL Layout

### ISSUE THREAD

**Issue by RaiN3772** [nextui-org/nextui#3099] opened 2024-05-27 19:44 UTC
### NextUI Version

2.3.6

### Describe the bug

When switching the language direction from LTR (left-to-right) to RTL (right-to-left), the Pagination component displays the selected page number incorrectly. Specifically, when the selected page is the first page in LTR mode, switching to RTL mode causes the component to display the last page as selected, even though the actual selected page remains the first page. Changing the page fixes the display issue, but this behavior is confusing and should be corrected without requiring user interaction.

### Steps to Reproduce the Bug or Issue

1. Render the Pagination component with multiple pages (e.g., 10 pages).
2. Ensure the initial selected page is set to the first page.
3. Change the layout direction from LTR to RTL.
4. Observe the displayed selected page number.

### Expected behavior

The Pagination component should correctly display the first page as selected when switching from LTR to RTL without requiring any user interaction.

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/56936836/13c01569-2101-4ed4-ad39-ae692ef6a259)
![image](https://github.com/nextui-org/nextui/assets/56936836/d6a122f4-cc1b-4a02-b215-93bbd86294e0)

### Operating System Version

- Web

### Browser

Opera

**Comment by ryo-manba** [comment] 2024-06-13 02:51
Looks like a duplicate of https://github.com/nextui-org/nextui/issues/2858

**Closed** 2024-06-13 04:05 UTC
Labels: 🐛 Type: Bug
