### ISSUE TITLE
[BUG] - How can I defined custom breakpoints in createTheme?

### ISSUE THREAD

**Issue by siamahnaf** [nextui-org/nextui#823] opened 2022-10-14 05:10 UTC
### Describe the bug

Hello, how can I define custom breakpoints. I am not finding any documentation about custom breakpoints. I am trying with this-

`theme.ts`-
```
export const darkTheme = createTheme({
    type: 'dark',
    theme: {
        colors: {
            background: "#363449",
            text: '#fff',
            primary: '#87ef17',
            myDarkColor: '#ff4ecd',
            primarySolidHover: '#fff316',
        },
        space: {},
        fonts: {},
        breakpoints: {
            xxs: 360,
            ...........,
            xxl: 1920
        }
    }
});
```

And then in `Container` component
```
<Container xxl>
     ....
</Container>
```

### Steps to Reproduce the Bug or Issue

Then after running my site, I can see custom breakpoints width not working as well.

### Expected behavior

It should be capable to define custom breakpoints in createTheme and then it should work anywhere search as container tag.

### Operating System Version

Windows

### Browser

Chrome

**Comment by Xariwey** [comment] 2022-10-14 08:47
<Container css={{ maxWidth: '$breakpoints$xxs' }}>

**Comment by siamahnaf198** [comment] 2022-10-14 08:51
Then how can I do responsive css

**Comment by siamahnaf198** [comment] 2022-10-14 09:35
> 

Not working. Please tell me the actual way

**Comment by Xariwey** [comment] 2022-10-14 10:55
look at this example maybe it can help u

https://codesandbox.io/s/nextui-custom-breakpoints-media-queries-demo-ixiy3h

**Comment by siamahnaf198** [comment] 2022-10-15 06:25
Then responsive css not working-

```
export const theme= createTheme({
    type: 'light',
    theme: {
        colors: {
            background: "#363449",
            text: '#fff',
            primary: '#87ef17',
            myDarkColor: '#ff4ecd',
            primarySolidHover: '#fff316',
        },
        space: {},
        fonts: {},
        breakpoints: {
            xxl: "120px",
            smd: "768px",
        }
    }
})
```
Then css for responsiveness -

```
<Text css={{
  color: "yellow",
  "@smd": {
    color: "red"
  }
}}>Hello World</Text>
```

This is not working. Can you describe briefly about custom breakpoints with responsive css.

**Comment by Xariwey** [comment] 2022-10-15 07:52
https://codesandbox.io/s/nextui-styledcomponent-demo-ixiy3h

use styled components using stitches css
https://nextui.org/docs/theme/override-styles#using-the-styled-function
https://stitches.dev/docs/variants

**Comment by siamahnaf198** [comment] 2022-10-15 08:02
This is disappointing. I hope you will make it easier.

**Comment by siamahnaf198** [comment] 2022-10-15 19:13
If it can be done with css props. Then it will be easier. Styled component is disappointing.

**Comment by Xariwey** [comment] 2022-10-15 20:26
is this what u want to do?

```js
      <Text
        css={{
          color: "yellow",
          "@media(max-width: 320px)": {
            color: "red"
          }
        }}
      >
        Hello World
      </Text>

```

**Comment by siamahnaf198** [comment] 2022-10-17 10:08
It will be more user friendly when we can add custom breakpoints and we can use that in `css`, props.

**Comment by audifaxdev** [comment] 2022-11-23 23:10
I believe this is a duplicate of https://github.com/nextui-org/nextui/issues/855
but I will paste my answer here as well

@siamahnaf198   I was able to easily make my own custom breakpoints by forking nextui project, then editing the default breakpoints https://github.com/nextui-org/nextui/blob/f85a569b4782e99124c752269867272dc91f6313/packages/react/src/theme/common.ts line 154

```
yarn install && yarn build:nextui
cd packages/react && yarn pack
//then in your project
npm i ~/path/to/package.tgz
```

I know it's not ideal, but it's an easy and quick workaround for now.

If you look at https://github.com/nextui-org/nextui/blob/f85a569b4782e99124c752269867272dc91f6313/packages/react/src/theme/stitches.config.ts

The nextui project seems to need to hold a ref to the stitches theme object which is created at lib initialization.

The feature we need would probably require quite a bit of work, I'm just getting into nextui and stitches so I can't tell.

**Comment by Mominadar** [comment] 2022-12-08 07:56
I want to create custom breakpoints directly in theme object. Is this possible yet?

**Comment by jrgarciadev** [comment] 2023-08-02 02:38
Hey please update to v2 https://nextui.org/blog/nextui-v2 and use TailwindCSS built-in breakpoints

**Closed by jrgarciadev** 2023-08-02 02:38 UTC
Labels: bug
