### ISSUE TITLE
[BUG] - Cannot update a component during rendering with RadioGroup component

### ISSUE THREAD

**Issue by drokbers** [nextui-org/nextui#2646] opened 2024-04-05 01:04 UTC
### NextUI Version

2.2.10

### Describe the bug

my code:

```
     <RadioGroup
            label="Select one?"
            defaultValue={currently_working}
            name="currently_working"
            orientation="horizontal"
            onChange={handleRadioChange}
          >
            <Radio value="yes">Yes</Radio>
            <Radio value="no">No</Radio>
          </RadioGroup>
```

So when I remove the radiogrup there is no error in my code, all things working well this error coming when I use radiogrup.

> Warning: Cannot update a component (`HotReload`) while rendering a different component (`NextUI.RadioGroup`). To locate the bad setState() call inside `NextUI.RadioGroup`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render

> import.mjs:140 Uncaught TypeError: Cannot destructure property 'isInvalid' of 'state.displayValidation' as it is undefined.

### Steps to Reproduce the Bug or Issue

1) There is a open form button in my website
2) When I click button the form page is coming up with radio group
3) page is crashing and error coming up

### Expected behavior

radio button render well 

### Operating System Version

macOS 

### Browser

Chrome

**Comment by wingkwong** [comment] 2024-04-05 03:43
@drokbers I couldn't reproduce the issue based on the given code. Can you provide a minimal reproducible environment (e.g. Stackblitz) please?

**Comment by drokbers** [comment] 2024-04-05 18:22
> @drokbers I couldn't reproduce the issue based on the given code. Can you provide a minimal reproducible environment (e.g. Stackblitz) please?

Hi @wingkwong  thank you for quick response, I put my dependencies and code example on stackblitz but it didn't give same error, but in my real project if I put radiogroup its giving the error. Let me test more

https://stackblitz.com/edit/stackblitz-starters-ymaqqw?file=app%2Fpage.tsx

**Comment by drokbers** [comment] 2024-04-05 18:28
I just changed my version  2.2.10 to  "^2.1.13" and it fixed

**Comment by wingkwong** [comment] 2024-04-09 04:42
@drokbers so the issue can be reproducible only in 2.2.10 but not ^2.1.13?  I'm a bit confused as I saw 2.2.10 is used in the provided stackblitz link.

**Comment by drokbers** [comment] 2024-04-09 04:46
> @drokbers so the issue can be reproducible only in 2.2.10 but not ^2.1.13? I'm a bit confused as I saw 2.2.10 is used in the provided stackblitz link.

Yeah, In 2.2.10 I have the problem mentioned. I was using it before 2.1.13, so the problem was fixed when I backdated the version on package.json.

**Comment by wingkwong** [comment] 2024-04-09 08:33
but I didn't see the reported error in your stackblitz which is using 2.2.10

**Comment by ryo-manba** [comment] 2024-05-31 08:09
Since the issue could not be reproduced, we are closing this issue.
If the problem persists, please feel free to reopen.

**Closed by ryo-manba** 2024-05-31 08:09 UTC
Labels: 🐛 Type: Bug
