### ISSUE TITLE
[BUG] - DropdownItem onPress not useable with keyboard (un-deprecate onAction)

### ISSUE THREAD

**Issue by LeakedDave** [nextui-org/nextui#3418] opened 2024-07-05 20:51 UTC
### NextUI Version

2.4.2

### Describe the bug

When using DropdownItem, if you give it an onPress prop it correctly fires that event when you click or tap the item. However, if you navigate through the Dropdown using the keyboard, pressing Space key does not fire onPress (like it does for normal Button elements)

The fix is to use onAction, which is marked as deprecated. Why is onAction deprecated? I believe onAction should be un-deprecated. It requires a lot of extra lines of code to add keys and use onAction on DropdownMenu. onAction on DropdownItem works just fine, let's un-deprecate it, or fix onPress to fire correctly when using the keyboard space key while focused.

### Operating System Version

MacOS

### Browser

Chrome

**Comment by ryo-manba** [comment] 2024-07-06 03:06
I couldn't reproduce the issue. Could you please provide a minimal reproduction example using Stackblitz?

https://github.com/nextui-org/nextui/assets/76232929/a8deeae0-bf8d-460c-b092-4aec8ab08d32

**Comment by LeakedDave** [comment] 2024-07-06 04:14
Oops! Looks like this was a bug happening in 2.4.1, upgrading and testing in 2.4.2, isPressed is being called correctly. I was using 2.4.1 because of an issue with the Avatar disableAnimation errors

**Comment by ryo-manba** [comment] 2024-07-06 05:29
I will close this issue then. If you encounter any other problems, please open a new issue.

**Closed by ryo-manba** 2024-07-06 05:29 UTC
Labels: 🔎 Status: More Info Needed
