### ISSUE TITLE
[BUG] - Children lose formatting in button

### ISSUE THREAD

**Issue by zbas** [nextui-org/nextui#2671] opened 2024-04-08 16:27 UTC
### NextUI Version

2.0.27

### Describe the bug

Content inside a Button does not respect formatting as it does in other elements.

### Steps to Reproduce the Bug or Issue

Try using something like the following:

```
<Button className="display: block h-20">
<span className="display: flex w-60 h-20 items-center gap-10">
	<span className="justify-start h-fit w-40 text-wrap">
		In a Button context, this content doesn't wrap.
	</span>
	<span className="justify-end h-fit w-10"> 
	D 
	</span>	
</span>				
</Button>
```

### Expected behavior

I expected that Button would respect formatting the same way other elements do, in the example given the text would wrap as it does in the other contexts.

### Screenshots or Videos

![buttonFormatting](https://github.com/nextui-org/nextui/assets/6650190/61e4e708-6579-4936-b26c-c677ea5e9cc3)

### Operating System Version

Windows 10

### Browser

Firefox

**Comment by zbas** [comment] 2024-04-08 17:52
@wingkwong Should I close the issue? Is the intended behaviour that content should be whitespace-nowrap as in packages/core/theme/src/components/button.ts?

**Comment by wingkwong** [comment] 2024-04-09 03:03
@zbas lemme reconfirm with the team and get back to you later. Will leave this issue open first.

**Comment by wingkwong** [comment] 2024-04-11 13:18
@zbas confirmed with Junior, it's intended to use `whitespace-nowrap` to avoid buttons with more than one line. Closing this issue now.

**Closed by wingkwong** 2024-04-11 13:18 UTC
Labels: bug
