### ISSUE TITLE
[BUG] - Textarea label is smaller than the label of Input for lg size

### ISSUE THREAD

**Issue by xylish7** [nextui-org/nextui#3073] opened 2024-05-24 13:00 UTC
### NextUI Version

2.3.6

### Describe the bug

It seems like the label of textarea is smaller than the label of other Input.

The font size of textarea label is `var(--nextui-font-size-small)` while the one of the normal input is `var(--nextui-font-size-medium)`

![image](https://github.com/nextui-org/nextui/assets/24867712/76c806c9-0b2a-44ef-b7bc-7beea6bb21ee)

### Steps to Reproduce the Bug or Issue

Render an Input component and a Textarea component. The label font size of Textarea is smaller than the one from Input.

### Expected behavior

Both Input and Textarea should have the same font size.

### Operating System Version

Windows

### Browser

Chrome

**Comment by wingkwong** [comment] 2024-05-26 09:52
Can you please share your code? Both are text-small on my side.

![image](https://github.com/nextui-org/nextui/assets/35857179/1ff98d4e-3fe5-4de4-a640-63bfbc9c9aa1)

**Comment by xylish7** [comment] 2024-05-27 07:44
Sorry @wingkwong , the actual issue is having both an `Input` and `Textare` with `size` prop equal to `lg`. For the textarea, the palceholder gets bigger, but not the label.

![image](https://github.com/nextui-org/nextui/assets/24867712/a84896c2-9227-4b3f-a489-3625e5736901)


You can check it here:
https://stackblitz.com/edit/stackblitz-starters-c4jmxj?file=app%2Fpage.tsx

**Comment by ShrinidhiUpadhyaya** [comment] 2024-06-04 16:25
The font-size for `Input` when `labelPlacement` is `outside-left` is also smaller, when compared to `labelPlacement` of `inside` and `outside`. While in TextArea it is smaller for all `labelPlacement`. In all the cases the `size` is `lg` .

Screenshot of Input Component

![image](https://github.com/nextui-org/nextui/assets/8769408/9db2dd21-2ad6-4acd-8392-429734ef268c)

Can i work on this issue?

**Comment by wingkwong** [comment] 2024-06-04 16:58
reassigned to @ShrinidhiUpadhyaya since i'm fully occupied by other issues.

**Comment by ShrinidhiUpadhyaya** [comment] 2024-06-06 14:15
### Input font values:-
![image](https://github.com/nextui-org/nextui/assets/8769408/dfd1e04a-ea32-4bd2-9561-b99413d55dc6)

### TextArea font values:-
![image](https://github.com/nextui-org/nextui/assets/8769408/223d5ec9-71d3-4c53-b54a-ea6beeaa18d6)

### Question
The values marked in **_red_** are incorrect values. I think the **_red_** values for Input font are incorrect. Regarding the **_red_** values for TextArea, is it a design decision or do i need to fix them, so that the font sizes for Label in `Input` and `TextArea` are same?

**Comment by fschoenfeldt** [comment] 2024-11-01 09:22
Can reproduce, could it be that the `DatePicker` has the same issue?

| Component     | Size  | Calculated Pixels |
|---------------|-------|-------------------|
| Datepicker    | sm    | 12px              |
|               | md    | 14px              |
|               | lg    | **14px (!)**          |
| Textarea      | sm    | 12px              |
|               | md    | 14px              |
|               | lg    | **14px (!)**          |
| Autocomplete  | sm    | 12px              |
|               | md    | 14px              |
|               | lg    | 16px              |

**Comment by wingkwong** [comment] 2024-11-19 15:26
will be handled by core team member for this issue.

**Closed** 2024-12-26 13:58 UTC
Labels: 🐛 Type: Bug, 📦 Scope : Components
