### ISSUE TITLE
[BUG] - Unexpected behaviour on autocompleteItem select

### ISSUE THREAD

**Issue by Mike3386** [nextui-org/nextui#3449] opened 2024-07-11 16:04 UTC
### NextUI Version

2.4.2

### Describe the bug

On mobile, when you tap on AutocompleteItem and there is other autocomplete under it, it makes element under focused.

### Your Example Website or App

[CodeSandbox](https://codesandbox.io/p/devbox/nextui-click-bug-example-forked-y7d6k5?workspaceId=40529a99-eb8e-4761-9feb-b70577eadce0&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clyhd5phz00063j6n5e1bd59d%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clyhd5phy00033j6nsnjmp43g%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clyhd5phy00043j6ngnljz220%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clyhd5phy00053j6ngs11dsvt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clyhd5phy00033j6nsnjmp43g%2522%253A%257B%2522id%2522%253A%2522clyhd5phy00033j6nsnjmp43g%2522%252C%2522activeTabId%2522%253A%2522clyhf311j003l3j6nbrybifqf%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clyhd5phy00023j6nt2ky1xwv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FApp.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A27%257D%255D%257D%252C%257B%2522id%2522%253A%2522clyheiz8o00023j6nzr9ugtsh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2487%252C%2522startColumn%2522%253A9%252C%2522endLineNumber%2522%253A2487%252C%2522endColumn%2522%253A19%257D%255D%252C%2522filepath%2522%253A%2522%252Froot%252F.cache%252Ftypescript%252F5.4%252Fnode_modules%252F%2540types%252Freact%252Findex.d.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clyhf311j003l3j6nbrybifqf%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clyhd5phy00053j6ngs11dsvt%2522%253A%257B%2522id%2522%253A%2522clyhd5phy00053j6ngs11dsvt%2522%252C%2522activeTabId%2522%253A%2522clyheme0r000y3j6ncswr5da5%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522clyhd5qsl001j3j6nocf0t9gz%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522DOCS%2522%252C%2522path%2522%253A%2522%252Feditors%252Fweb%252Fvscode-web%2522%252C%2522id%2522%253A%2522clyhd60se00053j6n50y3lh9d%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clyhd6uhd001q3j6nehbtnyzm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A2222%252C%2522id%2522%253A%2522clyhd83mv001b3j6n7z3bmy3n%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clyhd8ipv00203j6npu2115zt%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522isCloud%2522%253Atrue%252C%2522id%2522%253A%2522clyhdbarr002g3j6n672bwye4%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522CHANGELOG%2522%252C%2522id%2522%253A%2522clyhejizl001d3j6nu2u725qs%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clyheme0r000y3j6ncswr5da5%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clyhd5phy00043j6ngnljz220%2522%253A%257B%2522id%2522%253A%2522clyhd5phy00043j6ngnljz220%2522%252C%2522activeTabId%2522%253A%2522clyhd6eq300173j6n2wxi07yk%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clyhd6eq300173j6n2wxi07yk%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to Reproduce the Bug or Issue

1. Open codesandbox
2. Open preview in new tab
3. Open devTools
4. Toggle device toolbar
5. Open first autocomplete
6. Tap on autoCompleteItem that has autocomplete under it
7. See bug

### Expected behavior

As a user, i expected to close list of autoCompleteItems and element under might be not focused

### Screenshots or Videos

Display how it looks

https://github.com/nextui-org/nextui/assets/14157926/223e1323-3bbe-4bbf-ad2a-ba2d5f4e71f3

### Operating System Version

Windows

### Browser

Chrome

**Comment by navneetthakor** [comment] 2024-07-20 05:39
Hello @wingkwong can you please assing this issue to me

**Comment by navneetthakor** [comment] 2024-07-21 16:53
@wingkwong I have tried to discover issue well but nothing is happening as you mentioned here.

Uploading Untitled video - Made with Clipchamp.mp4…

**Comment by wingkwong** [comment] 2024-07-22 02:17
@navneetthakor I just tested on the given sandbox again and i can reproduce the issue. you need to do it in mobile viewport. Also the video you provided is now shown. please double check.

**Comment by jhargett** [comment] 2024-08-19 20:00
I am also experiencing this issue but only on mobile viewport

**Comment by mkrystkowicz** [comment] 2024-08-21 08:06
Happens on modal as well, for example when you click on close button or outside modal

**Comment by jedi04** [comment] 2024-09-06 17:40
I am also facing this issue. Any fix for this?

**Comment by wingkwong** [comment] 2024-09-07 10:36
@navneetthakor any update?

**Comment by mkrystkowicz** [comment] 2024-09-08 10:24
I have switched to react-select package not to confuse mobile users (recommend this approach, less effort than trying to fix that), tried preventing mouse touch but the bug was still there.

**Comment by slimshreydy** [comment] 2024-10-12 06:27
Running into a similar issue. If I have multiple Autocompletes, the first one works as expected but then with the second one, the search value (the value of the input in the autocomplete) gets reset automatically after 2 characters are typed. I only see this issue on Chrome iOS.

**Comment by macci001** [comment] 2024-10-13 04:27
Seems like this issue occurs due to the `chromium` bug. Due to this, the problem got propagated to react-aria's usePress and NextUI library.

Issue Summary: 
* When there is a `touchStart` event triggered on element and that element moves out of the DOM immediately, the element beneath will get the `click` event triggered.
* Due to the this, it will feel like the element beneath the overlay is getting clicked, when overlay is clicked. (This happens only during touch.)

The ReactSpectrum team has already put up the fix for this in usePress: [Fix for onClick triggered on wrong target](https://github.com/adobe/react-spectrum/pull/7026). 
This fix is already included in v2.22.3 of `RA interactions`
We are currently using the the v2.21.3 of `RA interactions` and using the latest version of the dependency should solve the problem.

Note:
* Since the issue occurs when the element moves out of the DOM immediately, if there is some delay in its exit, we would not see this issue.
* An example of above can be seen after [3845](https://github.com/nextui-org/nextui/pull/3845) pr was added to the canary. This PR added fixed the exit animation of the pop-over in the autocomplete. Since this avoids the immediate exit of the target, after this PR the issue seems only to persist in case of disabled-animation. 


Some of the references:
* [Chromium Bug](https://issues.chromium.org/issues/40732224)
* [FireFox Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1692033)
* ReactAria's issue for this bug patch: [1513](https://github.com/adobe/react-spectrum/issues/1513)
* ReactSpectrum's patch pr: [7026](https://github.com/adobe/react-spectrum/pull/7026)

**Closed** 2024-11-04 14:53 UTC
Labels: 🐛 Type: Bug, 📦 Scope : Components
