### ISSUE TITLE
[BUG] - Inputs focus overflows wrapper UI

### ISSUE THREAD

**Issue by uigywnkiub** [nextui-org/nextui#3441] opened 2024-07-10 11:54 UTC
### NextUI Version

2.4.2

### Describe the bug

Inputs focus overflows wrapper UI when i focus on the for example via Tab button.

### Steps to Reproduce the Bug or Issue

1) Create any input field. 2) Try to focus on them for example via button Tab. (in my case parent do not have paddings)

### Expected behavior

I must not overflow parent wrapper with outlined lines, my temp fix is set padding left and right to parent to fix it overflows.

### Screenshots or Videos

<img width="570" alt="image" src="https://github.com/nextui-org/nextui/assets/29861553/7163c110-d61e-4527-8ffb-1b82c29f0553">

https://github.com/nextui-org/nextui/assets/29861553/399d6210-cc7a-4814-b1a7-bec736a76ecc

### Operating System Version

- OS: macOS

### Browser

Chrome

**Comment by uigywnkiub** [comment] 2024-07-10 13:01
> please share a minimal reproducible environment

```js
    <Accordion
      isCompact
      hideIndicator
      onExpandedChange={onExpandedChange}
      defaultExpandedKeys={isInitialExpanded}
      className='p-0'
    >
      <AccordionItem
        key={ACCORDION_ITEM_KEY}
        isCompact
        aria-label={accordionTitle}
        title={accordionTitle}
        classNames={{
          title: 'text-center hover:opacity-hover',
        }}
      >
        <Switch
          isDisabled={pending}
          color='success'
          name='isIncome'
          value='isIncome'
          aria-label='Income Switch'
          onValueChange={(isSelected) => setIsSwitchedOn(isSelected)}
        >
          Income
        </Switch>
        <Input
          isDisabled={pending}
          isRequired
          type='text'
          ...
```

**Comment by wingkwong** [comment] 2024-07-10 13:11
That's not minimal reproducible environment.

**Comment by uigywnkiub** [comment] 2024-07-10 13:13
> That's not minimal reproducible environment.

What is minimal reproducible environment? Why are you always need this? Refactor issue to user type this reproducible environment!

**Comment by abhinandan-verma** [comment] 2024-07-10 14:20
@uigywnkiub  Sir, has meant to share  your code in some virtual reproducing enviroment something like 
[https://codesandbox.io/p/devbox/aged-sun-82n993?utm_medium=sandpack](url)
OR
[https://stackblitz.com/edit/react-ytb8lu?file=src%2FApp.js](url)

You can use these to virtual  app showing the bug. I will help us to debug more efficiently.
I hope you understand it :)

**Comment by abhinandan-verma** [comment] 2024-07-20 14:10
@uigywnkiub I could solve your issue if you could provide MRE

**Comment by abhinandan-verma** [comment] 2024-07-27 04:29
@uigywnkiub  I have got your point, but the issue is not visible in storybook. There is no overflow with the following code

```zsh
<div className="w-full max-w-2xl">
    <Input {...args} className="w-full bg-success-50" />
</div>
```

<img width="739" alt="Screenshot 2024-07-27 at 9 54 40 AM" src="https://github.com/user-attachments/assets/57f06681-e8e8-4347-af92-c80ec2d3cd96">


Kindly check if you having some tailwind issue like `overflow-hidden` and `max-w-` togethar.
I hope it should solve your issue.

**Comment by wingkwong** [comment] 2024-08-31 17:17
Closing - no MRE provided.

**Closed by wingkwong** 2024-08-31 17:17 UTC
Labels: 📃 Status: Reproducible Environment Needed
