### ISSUE TITLE
[BUG] - DropdownItem routing don't work as expected

### ISSUE THREAD

**Issue by CMOISDEAD** [nextui-org/nextui#3219] opened 2024-06-08 23:12 UTC
### NextUI Version

2.4.1

### Describe the bug

I'm using Vite, React, and React Router DOM, following the routing guide provided by NextUI. With most components that allow this functionality, everything works fine, but with DropdownItem the page reloads.

![image](https://github.com/nextui-org/nextui/assets/51010598/7c495c12-be1e-403a-bc0d-edc8b15e81ff)

![image](https://github.com/nextui-org/nextui/assets/51010598/40814ca9-6f39-4759-b019-0e6995ad0fce)

![image](https://github.com/nextui-org/nextui/assets/51010598/78468c62-40ec-4722-83b2-4e59a9560755)

![image](https://github.com/nextui-org/nextui/assets/51010598/df2c6dcf-0ead-4597-8d63-98d10500261f)

In the related video, you can see that when the href property is used on a DropdownItem, it triggers a full page reload instead of the expected Link behavior.

### Steps to Reproduce the Bug or Issue

use href in DropdownItem

### Expected behavior

Redirect the page without full reload

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/51010598/e0f48455-9b42-4e3d-8b2e-7ed96166610d

### Operating System Version

Linux

### Browser

Chrome

**Comment by wingkwong** [comment] 2024-06-09 03:09
1. for dropdown item href issue, are you using npm? if so, can you also use pnpm to see if the issue is still there?
2. for link full page reload issue, this has been fixed previously. Can you try remove node_modules and reinstall? also you may try to use pnpm.

**Comment by CMOISDEAD** [comment] 2024-06-09 04:51
I am already using pnpm, and the problem persists after removing and reinstalling node_modules. The other components work fine with the href property

**Comment by chen-yan** [comment] 2024-06-10 06:28
> 1. for dropdown item href issue, are you using npm? if so, can you also use pnpm to see if the issue is still there?
> 2. for link full page reload issue, this has been fixed previously. Can you try remove node_modules and reinstall? also you may try to use pnpm.

ListboxItem works good after switch to pnpm. but this component'e routing still reloading the whole page.

[https://github.com/nextui-org/nextui/issues/3206](url)

**Comment by winchesHe** [comment] 2024-06-10 14:21
@CMOISDEAD It's not a issue for `dropdownItem` with href attr, it expressing default anchor behavior, just use `link` to route if don't want to reload the page

**Comment by chen-yan** [comment] 2024-06-11 01:38
As "dropdownItem" provide href attribute, It should have the same behavior as Link when href has value.

**Comment by winchesHe** [comment] 2024-06-11 01:44
This needs to be decided whether internal support is needed, current you could use `onPress/onClick` to add route navigate, or use `Link` component

**Comment by wingkwong** [comment] 2024-06-15 07:26
Fixed in https://github.com/nextui-org/nextui/pull/3240

**Closed by wingkwong** 2024-06-15 07:26 UTC
Labels: 🐛 Type: Bug, 📦 Scope : Components
