### ISSUE TITLE
[BUG] - Typescript error with DropdownItem

### ISSUE THREAD

**Issue by matteo-pkxp** [nextui-org/nextui#1691] opened 2023-09-25 09:45 UTC
### NextUI Version

2.1.13

### Describe the bug

Hello,
I have a type issue when using the Dropdown component, this is the code triggering the ts error:

```
<DropdownMenu aria-label="Profile Actions" variant="flat">
    { menuItems.map((entry) => (
        <DropdownItem key={entry.link} showDivider={entry.divider}>
            {entry.name}
        </DropdownItem>
    ))}
    <DropdownItem key="custom">Test123</DropdownItem>
</DropdownMenu>
```

The error is: `Type 'Element[]' is not assignable to type 'CollectionElement<object>'`.
The code runs fine and the result is as expected, that is a list of DropdownItems followed by the non-iterated "Test123" item, but the error (that I couldn't suppress) prevents me from building the app for production.

If I wrap it with a fragment `<></>`, which makes the TS error disappear, this time the error is at runtime and becomes `TypeError: Cannot convert a Symbol value to a string`.

Any idea on how to make it work? I have custom element at the bottom of this dropdown, that doesn't match the structure of the iterated elements.

### Steps to Reproduce the Bug or Issue

I'm using Typescript 5.1.6 and NextJS 13.4.13

### Expected behavior

There should be either no runtime or linter errors.

### Operating System Version

Windows with Linux Subsystem 2.0 (Debian LTS)

### Browser

Chrome

**Comment by matteo-pkxp** [comment] 2023-09-25 09:57
I found a not-so-elegant solution to ignore the TS error:

```
<DropdownMenu aria-label="Profile Actions" variant="flat">
{[
  // @ts-ignore
  menuItems.map((entry) => (
      <DropdownItem key={entry.link}>
          {entry.name}
      </DropdownItem>
  )),
  <DropdownItem key="custom">Test123</DropdownItem>,
]}
</DropdownMenu>
```

This suppresses the TS error, renders the Dropdown as expected and throws no runtime errors, but I'm sure there's a better solution.

**Comment by matteo-pkxp** [comment] 2023-09-25 10:11
Option number 2, which is probably the best one:

```
 <DropdownMenu aria-label="Profile Actions" variant="flat">
   <DropdownSection>
      { menuItems.map((entry) => (
          <DropdownItem key={entry.link} showDivider={entry.divider}>
              {entry.name}
          </DropdownItem>
      ))}
    </DropdownSection>
    <DropdownItem key="custom">Test123</DropdownItem>
</DropdownMenu>
```

The only downside here is the aria-label warning, because It's a titleless section.

Not sure if I should close the issue though. I don't think the errors I encountered are expected.

**Comment by lalalazero** [comment] 2023-09-27 02:46
Hello~

I did some research to figure this out. so the underlying of menu is using react-aria-components. if you wish to render dynamic items, I think the proper way should go with this

```
 <DropdownMenu aria-label="Profile Actions" variant="flat" items={menuItems}>
   {(item) => <DropdownItem key={item.key} showDivider={item.divider} />}
</DropdownMenu>
```

**Comment by matteo-pkxp** [comment] 2023-09-27 08:10
Hi!
Thanks for the suggestion, this is surely something that's good to know. 
Unfortunately, it doesn't fix the issue. 
```
Type '(item: MenuEntry) => JSX.Element' is not assignable to type 'CollectionChildren<object>'.
Type '(item: MenuEntry) => JSX.Element' is not assignable to type '(item: object) => CollectionElement<object>'.
Types of parameters 'item' and 'item' are incompatible.
Property 'name' is missing in type '{}' but required in type 'MenuEntry'.ts(2322)
```

Looks like it's a Typescript incompatibility of some sort. The dropdown gets rendered as intended, it's just the compiler that goes crazy. 

Also, if I do something like this below, only the "custom" element gets rendered:

```
 <DropdownMenu aria-label="Profile Actions" variant="flat" items={menuItems}>
   {(item) => <DropdownItem key={item.key} showDivider={item.divider} />}
   <DropdownItem key="custom">Test123</DropdownItem>
</DropdownMenu>
```

The only solution is to use the DropdownSection component, that supports the `items` prop.

**Comment by carlosriveroib** [comment] 2023-10-01 22:09
I'm having same issue

**Comment by xavier-villelegier** [comment] 2023-11-04 17:06
Hey ! I see you closed this in 2.2.0 @jrgarciadev ?

I'm still having this issue with the following in 2.2.1:

```ts
<Dropdown placement="bottom-end">
  <DropdownMenu aria-label="Profile Actions" variant="flat">
    {session.user?.isAdmin && (
      <DropdownSection title="Admin" showDivider>
        <DropdownItem key="prisma">Whatever</DropdownItem>
      </DropdownSection>
    )}
  </DropdownMenu>
</Dropdown>
```

Same symptoms, ts-error, then runtime error if wrapping it inside a fragment 😕

**Comment by aaronhawkey** [comment] 2023-11-09 21:00
My code that is experiencing the same error in 2.2.8:

```ts
        {
          notificationsData.map((notification) => {
            return (
              <DropdownItem key={notification.id}>
                <Notification
                  body={notification.body}
                  date={notification.createdAt}
                  read={notification.read}
                />
              </DropdownItem>
            )
          })
        }
```

**Comment by jrgarciadev** [comment] 2023-11-10 11:34
Hey guys I'm trying to figure out ways to fix this, the [react-aria collection API](https://react-spectrum.adobe.com/react-stately/collections.html) only accepts specific components as children (Item, Section) to build the collection, that's why it fails when trying to pass custom components.


@aaronhawkey did you try using the Dropdown dynamic render?

```tsx
import React from "react";
import {Dropdown, DropdownTrigger, DropdownMenu, DropdownItem, Button} from "@nextui-org/react";

export default function App() {

  const notificationsData = [
    {
      key: "1",
      read: false,
      body: "First message",
      createdAt: null
    },
    {
      key: "2",
      read: false,
      body: "Second Message",
      createdAt: null
    },
    {
      key: "3",
      read: false,
      body: "Third message",
      createdAt: null
    },
  ];

  return (
    <Dropdown>
      <DropdownTrigger>
        <Button 
          variant="bordered" 
        >
          Open Menu
        </Button>
      </DropdownTrigger>
      <DropdownMenu aria-label="Notifications" items={notificationsData}>
        {(notification) => (
          <DropdownItem  key={item.key} textValue={notification.body}>
             <Notification
                  body={notification.body}
                  date={notification.createdAt}
                  read={notification.read}
                />
          </DropdownItem>
        )}
      </DropdownMenu>
    </Dropdown>
  );
}

```

**Comment by codedotspirit** [comment] 2023-11-19 13:29
Hey, I'm struggling with a similar issue, although in my case it's with the `DropdownSection`:
```ts
<DropdownSection showDivider key={"notifications"} items={notifications}>
  {(item: any) => (
    <DropdownItem
      key={item.id} 
      onPress={notificationPressHandler}
      className={styles.notification__wrapper}
    >
      <span className={styles.notification__topic}>{item.topic}</span>
      <p className={styles.notification__content}>{item.content}</p>
    </DropdownItem>
  )}
</DropdownSection>
```

This is only a TypeScript error, I'll be using ``ts-ignore`` for now to avoid it. Components render fine.

**Comment by begalinsaf** [comment] 2024-03-03 06:53
you can try this bad solution

```javascript
 let dropdownItems = [
    {
      key: 'profile',
      label: 'Profile',
    },
    {
      key: 'signout',
      label: 'Signout',
    },
  ];

  if (auth?.user.role !== 'USER') {
    dropdownItems.push({
      key: 'dashboard',
      label: 'Dashboard',
    });
  }
  
  //return
  
             <DropdownMenu
                aria-label='dynamic'
                items={dropdownItems}
              >
                {(item) => (
                  <DropdownItem
                    key={item.key}
                    color={item.key === 'signout' ? 'danger' : 'default'}
                    className={item.key === 'signout' ? 'text-danger' : ''}
                  >
                    {item.label}
                  </DropdownItem>
                )}
              </DropdownMenu>
```

**Comment by aaronhawkey** [comment] 2024-03-11 15:05
> Hey guys I'm trying to figure out ways to fix this, the [react-aria collection API](https://react-spectrum.adobe.com/react-stately/collections.html) only accepts specific components as children (Item, Section) to build the collection, that's why it fails when trying to pass custom components.
> 
> @aaronhawkey did you try using the Dropdown dynamic render?
> 
> ```tsx
> import React from "react";
> import {Dropdown, DropdownTrigger, DropdownMenu, DropdownItem, Button} from "@nextui-org/react";
> 
> export default function App() {
> 
>   const notificationsData = [
>     {
>       key: "1",
>       read: false,
>       body: "First message",
>       createdAt: null
>     },
>     {
>       key: "2",
>       read: false,
>       body: "Second Message",
>       createdAt: null
>     },
>     {
>       key: "3",
>       read: false,
>       body: "Third message",
>       createdAt: null
>     },
>   ];
> 
>   return (
>     <Dropdown>
>       <DropdownTrigger>
>         <Button 
>           variant="bordered" 
>         >
>           Open Menu
>         </Button>
>       </DropdownTrigger>
>       <DropdownMenu aria-label="Notifications" items={notificationsData}>
>         {(notification) => (
>           <DropdownItem  key={item.key} textValue={notification.body}>
>              <Notification
>                   body={notification.body}
>                   date={notification.createdAt}
>                   read={notification.read}
>                 />
>           </DropdownItem>
>         )}
>       </DropdownMenu>
>     </Dropdown>
>   );
> }
> ```

Sorry for the late reply. I did and it worked for me.

**Comment by rkrajewski** [comment] 2024-04-02 17:40
None of the above solutions work for me for conditional rendering. I managed to implement a slightly tricky solution by using Type Guard, like so:

```typescript
function testT<T>(input: T | false | undefined | null): input is T {
  return Boolean(input)
}

function filter<T>(input: (T | false | undefined | null)[]): T[] {
  return input.filter(testT)
}

...


        <DropdownSection showDivider>
          {/* here comes the above 'filter 'function */}
          {filter([
            hasUnpublished && (
              <DropdownItem key="publish" className="text-success">
                Publish
              </DropdownItem>
            ),
            hasPublished && (
              <DropdownItem key="unpublish" className="text-warning">
                Unpublish
              </DropdownItem>
            ),
          ])}
        </DropdownSection>

```

**Comment by pablojsx** [comment] 2024-04-15 07:21
If you use a ternary if ? : you can return a empty DropdownItem with a className of "hidden". It will work.

**Comment by gamlerd13** [comment] 2024-07-07 03:28
This should work

`<DropdownMenu aria-label="Profile Actions" variant="flat">
      {menuItems ? (
        menuItems.map((entry) => (
          <DropdownItem key={entry.link} showDivider={entry.divider}>
            {entry.name}
          </DropdownItem>
        ))
      ) : (
        <DropdownItem>handle this, if there is no data</DropdownItem>
      )}
      <DropdownItem key="custom">Test123</DropdownItem>
    </DropdownMenu>`

**Comment by HM-Suiji** [comment] 2024-07-14 02:22
I think this is a big bug，DropdownMenu no longer seems to accept the prop of children.
in vscode,eslint error:不能将类型“{ children: (item: { link: string; name: string; }) => Element; "aria-label": string; items: { link: string; name: string; }[]; }”分配给类型“IntrinsicAttributes & Props<object> & { ref?: Ref<HTMLElement> | undefined; }”。
  类型“IntrinsicAttributes & Props<object> & { ref?: Ref<HTMLElement> | undefined; }”上不存在属性“children”。ts(2322)
and see the web ,error too:
![image](https://github.com/user-attachments/assets/d251ba15-6ad0-4bba-a357-cf8a5289b3e1)
`Error: Functions are not valid as a child of Client Components. This may happen if you return children instead of <children /> from render. Or maybe you meant to call this function rather than return it.
  <... aria-label=... items={[...]} children={function children}>`

**Comment by pablojsx** [comment] 2024-07-14 15:32
update nextui

**Comment by MFRamon** [comment] 2024-08-20 01:04
August 2024 and the issue is still happening is there a fix in the way?

**Comment by wingkwong** [comment] 2024-08-20 02:13
@MFRamon can you share your code reproducing the issue? I saw some usages aren't really bugs but misuse of the collection-based components.

**Comment by MFRamon** [comment] 2024-08-20 03:03
Sure @wingkwong . 

Actually a few hours back I figured out the issue. Apparently in version 2.4.6 is not happening, what I did was delete the node_modules folder and reinstall dependencies. Maybe I had the older version from nextui installed. Now It's rendering and working now. But posting the code here just in case you have any suggestions or comments.


` <Dropdown placement="right-end">
      <DropdownTrigger>
        <button>Button</button>
      </DropdownTrigger>
      <DropdownMenu variant="faded" aria-label="Dropdown menu title" className="w-[17vw] !p-0">
        <DropdownSection title={undefined} className="" id="section-titulos">
          <DropdownItem endContent={<button>Mark all as read</button>}>NOTIFICATIONS</DropdownItem>
        </DropdownSection>
        <DropdownSection title={undefined}>
          {items.map((item) => (
            <DropdownItem className="" key={item.key}>
              {item.label}
            </DropdownItem>
          ))}
        </DropdownSection>
        <DropdownSection title={undefined} className="" id="section-titulos">
          <DropdownItem>NOTIFICATIONS</DropdownItem>
        </DropdownSection>
      </DropdownMenu>
    </Dropdown>`
    
    
    Version in package.json is : 
    
     "@nextui-org/react": "^2.4.6",
     .
     .
     .
     
     Hopefully it's helpful for someone else

**Comment by wingkwong** [comment] 2024-08-20 03:32
I'm closing this issue since I couldn't reproduce any typescript error. Please note that this is a collection-based component and make sure there is at least one child there. The following example would fail because if `session.user?.isAdmin` is false, then there won't be any child which breaks the parsing.

```tsx
<Dropdown placement="bottom-end">
  <DropdownMenu aria-label="Profile Actions" variant="flat">
    {session.user?.isAdmin && (
      <DropdownSection title="Admin" showDivider>
        <DropdownItem key="prisma">Whatever</DropdownItem>
      </DropdownSection>
    )}
  </DropdownMenu>
</Dropdown>
```

**Closed by wingkwong** 2024-08-20 03:32 UTC
Labels: 🐛 Type: Bug

**Comment by simiel** [comment] 2024-10-27 18:43
wrap it in a fragment like this

                  <>
                  {Object.values(House).map((house) => (
                    <DropdownItem
                      key={house}
                      onClick={() => setFilterStatus(house)}
                    >
                      {house}
                    </DropdownItem>
                  ))}
                </>
