### ISSUE TITLE
[BUG] - DatePicker component  "isInvalid" prop not working as expact

### ISSUE THREAD

**Issue by goswamikaushik001** [nextui-org/nextui#3381] opened 2024-07-01 11:21 UTC
### NextUI Version

2.4.2

### Describe the bug

he `isInvalid` prop of the datepicker component displays an error message even when set to `false`.

### Steps to Reproduce the Bug or Issue

1. Use the datepicker component in a React application.
2. Set the `isInvalid` prop to `false`.
3. Observe that the error message is still displayed.

### Expected behavior

No error message should be displayed when `isInvalid` is set to `false`.

### Screenshots or Videos

code : 
![image](https://github.com/nextui-org/nextui/assets/163119411/c612c8f8-ba27-4d18-8458-67a6810a8a55)

preview
![image](https://github.com/nextui-org/nextui/assets/163119411/e91519cd-16bd-4b74-8909-069a62d72ad4)

### Operating System Version

- Ubuntu 22.04.4 LTS

### Browser

Other (add additonal context)

**Comment by wingkwong** [comment] 2024-07-01 11:49
I couldn't reproduce the issue using the given code, either in 2.4.2 / canary branch or with aria / native validationBehaviour. Can you double check the version? Also please provide a minimal reproducible environment for demonstration. Thanks.

**Comment by abhinandan-verma** [comment] 2024-07-27 04:53
@goswamikaushik001  if you are still having the issue kindly provide  a reproducible enviroment. so that we can help you.
as above mentioned it cannot be reproduced in latest version.
Maybe you just need to update.

**Comment by goswamikaushik001** [comment] 2024-07-27 05:06
thank you for assistant ,my issue is resolve






---- On Sat, 27 Jul 2024 10:23:48 +0530 Abhinandan ***@***.***> wrote ---





https://github.com/goswamikaushik001 if you are still having the issue kindly provide  a reproducible enviroment. so that we can help you.
 as above mentioned it cannot be reproduced in latest version.
 Maybe you just need to update.

**Comment by abhinandan-verma** [comment] 2024-07-27 05:07
Kindly close the issue. Happy to help you :)

**Comment by goswamikaushik001** [comment] 2024-07-27 05:14
thank you for help

**Closed** 2024-07-27 05:14 UTC
Labels: 📃 Status: Reproducible Environment Needed
